// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twilightproject/nyks/forks/attestation.proto

package types

import (
	fmt "fmt"
	_ "github.com/cosmos/gogoproto/gogoproto"
	proto "github.com/cosmos/gogoproto/proto"
	any "github.com/cosmos/gogoproto/types/any"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// ProposalType is the type of a proposal from the BTC chain
type ProposalType int32

const (
	PROPOSAL_TYPE_BTC_CHAINTIP     ProposalType = 0
	PROPOSAL_TYPE_BTC_DEPOSIT      ProposalType = 1
	PROPOSAL_TYPE_SWEEP_PROPOSAL   ProposalType = 2
	PROPOSAL_TYPE_CONFIRM_WITHDRAW ProposalType = 3
)

var ProposalType_name = map[int32]string{
	0: "PROPOSAL_TYPE_BTC_CHAINTIP",
	1: "PROPOSAL_TYPE_BTC_DEPOSIT",
	2: "PROPOSAL_TYPE_SWEEP_PROPOSAL",
	3: "PROPOSAL_TYPE_CONFIRM_WITHDRAW",
}

var ProposalType_value = map[string]int32{
	"PROPOSAL_TYPE_BTC_CHAINTIP":     0,
	"PROPOSAL_TYPE_BTC_DEPOSIT":      1,
	"PROPOSAL_TYPE_SWEEP_PROPOSAL":   2,
	"PROPOSAL_TYPE_CONFIRM_WITHDRAW": 3,
}

func (x ProposalType) String() string {
	return proto.EnumName(ProposalType_name, int32(x))
}

func (ProposalType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d55909fe5c7d951a, []int{0}
}

// Attestation is an aggregate of proposals that eventually becomes observed by
// all orchestrators
type Attestation struct {
	Observed bool     `protobuf:"varint,1,opt,name=observed,proto3" json:"observed,omitempty"`
	Votes    []string `protobuf:"bytes,2,rep,name=votes,proto3" json:"votes,omitempty"`
	Height   uint64   `protobuf:"varint,3,opt,name=height,proto3" json:"height,omitempty"`
	Proposal *any.Any `protobuf:"bytes,4,opt,name=proposal,proto3" json:"proposal,omitempty"`
}

func (m *Attestation) Reset()         { *m = Attestation{} }
func (m *Attestation) String() string { return proto.CompactTextString(m) }
func (*Attestation) ProtoMessage()    {}
func (*Attestation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d55909fe5c7d951a, []int{0}
}
func (m *Attestation) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Attestation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Attestation.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Attestation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Attestation.Merge(m, src)
}
func (m *Attestation) XXX_Size() int {
	return m.Size()
}
func (m *Attestation) XXX_DiscardUnknown() {
	xxx_messageInfo_Attestation.DiscardUnknown(m)
}

var xxx_messageInfo_Attestation proto.InternalMessageInfo

func (m *Attestation) GetObserved() bool {
	if m != nil {
		return m.Observed
	}
	return false
}

func (m *Attestation) GetVotes() []string {
	if m != nil {
		return m.Votes
	}
	return nil
}

func (m *Attestation) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *Attestation) GetProposal() *any.Any {
	if m != nil {
		return m.Proposal
	}
	return nil
}

func init() {
	proto.RegisterEnum("twilightproject.nyks.forks.ProposalType", ProposalType_name, ProposalType_value)
	proto.RegisterType((*Attestation)(nil), "twilightproject.nyks.forks.Attestation")
}

func init() {
	proto.RegisterFile("twilightproject/nyks/forks/attestation.proto", fileDescriptor_d55909fe5c7d951a)
}

var fileDescriptor_d55909fe5c7d951a = []byte{
	// 361 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x64, 0x91, 0xc1, 0x4e, 0xe2, 0x40,
	0x00, 0x86, 0x3b, 0xc0, 0x12, 0x76, 0xd8, 0x43, 0x33, 0x21, 0x9b, 0xd2, 0xec, 0x4e, 0x1a, 0xbc,
	0x34, 0x46, 0x5b, 0xa3, 0x67, 0x0f, 0x05, 0x6a, 0x68, 0xa2, 0xb4, 0x29, 0x4d, 0x88, 0x5e, 0x9a,
	0xa2, 0x43, 0x41, 0x48, 0xa7, 0xe9, 0x8c, 0x68, 0xdf, 0x40, 0x6f, 0x5e, 0x3d, 0xfb, 0x32, 0x1e,
	0x39, 0x7a, 0x34, 0xf0, 0x22, 0x86, 0x16, 0x30, 0xe8, 0xad, 0x5f, 0xff, 0x6f, 0x32, 0xff, 0xe4,
	0x87, 0x07, 0xfc, 0x7e, 0x3c, 0x1d, 0x87, 0x23, 0x1e, 0x27, 0xf4, 0x96, 0x5c, 0x73, 0x3d, 0x4a,
	0x27, 0x4c, 0x1f, 0xd2, 0x64, 0xc2, 0xf4, 0x80, 0x73, 0xc2, 0x78, 0xc0, 0xc7, 0x34, 0xd2, 0xe2,
	0x84, 0x72, 0x8a, 0xe4, 0x6f, 0xb6, 0xb6, 0xb2, 0xb5, 0xcc, 0x96, 0x6b, 0x21, 0x0d, 0x69, 0xa6,
	0xe9, 0xab, 0xaf, 0xfc, 0x84, 0x5c, 0x0f, 0x29, 0x0d, 0xa7, 0x44, 0xcf, 0x68, 0x70, 0x37, 0xd4,
	0x83, 0x28, 0xcd, 0xa3, 0xc6, 0x13, 0x80, 0x55, 0xe3, 0xeb, 0x0a, 0x24, 0xc3, 0x0a, 0x1d, 0x30,
	0x92, 0xcc, 0xc8, 0x8d, 0x04, 0x14, 0xa0, 0x56, 0xdc, 0x2d, 0xa3, 0x1a, 0xfc, 0x35, 0xa3, 0x9c,
	0x30, 0xa9, 0xa0, 0x14, 0xd5, 0xdf, 0x6e, 0x0e, 0xe8, 0x2f, 0x2c, 0x8f, 0xc8, 0xaa, 0x8e, 0x54,
	0x54, 0x80, 0x5a, 0x72, 0xd7, 0x84, 0x8e, 0x60, 0x25, 0x4e, 0x68, 0x4c, 0x59, 0x30, 0x95, 0x4a,
	0x0a, 0x50, 0xab, 0xc7, 0x35, 0x2d, 0xef, 0xa1, 0x6d, 0x7a, 0x68, 0x46, 0x94, 0xba, 0x5b, 0x6b,
	0xff, 0x05, 0xc0, 0x3f, 0xce, 0x1a, 0xbc, 0x34, 0x26, 0x08, 0x43, 0xd9, 0x71, 0x6d, 0xc7, 0xee,
	0x19, 0xe7, 0xbe, 0x77, 0xe9, 0x98, 0x7e, 0xd3, 0x6b, 0xf9, 0xad, 0x8e, 0x61, 0x75, 0x3d, 0xcb,
	0x11, 0x05, 0xf4, 0x1f, 0xd6, 0x7f, 0xe6, 0x6d, 0xd3, 0xb1, 0x7b, 0x96, 0x27, 0x02, 0xa4, 0xc0,
	0x7f, 0xbb, 0x71, 0xaf, 0x6f, 0x9a, 0x8e, 0xbf, 0xf9, 0x27, 0x16, 0x50, 0x03, 0xe2, 0x5d, 0xa3,
	0x65, 0x77, 0xcf, 0x2c, 0xf7, 0xc2, 0xef, 0x5b, 0x5e, 0xa7, 0xed, 0x1a, 0x7d, 0xb1, 0x28, 0x97,
	0x1e, 0x5f, 0xb1, 0xd0, 0x3c, 0x7d, 0x5b, 0x60, 0x30, 0x5f, 0x60, 0xf0, 0xb1, 0xc0, 0xe0, 0x79,
	0x89, 0x85, 0xf9, 0x12, 0x0b, 0xef, 0x4b, 0x2c, 0x5c, 0xed, 0x6d, 0xe6, 0x38, 0xdc, 0x59, 0xef,
	0x61, 0xbd, 0x1f, 0x4f, 0x63, 0xc2, 0x06, 0xe5, 0xec, 0xc9, 0x27, 0x9f, 0x01, 0x00, 0x00, 0xff,
	0xff, 0x63, 0xce, 0x67, 0x75, 0xea, 0x01, 0x00, 0x00,
}

func (m *Attestation) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Attestation) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Attestation) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Proposal != nil {
		{
			size, err := m.Proposal.MarshalToSizedBuffer(dAtA[:i])
			if err != nil {
				return 0, err
			}
			i -= size
			i = encodeVarintAttestation(dAtA, i, uint64(size))
		}
		i--
		dAtA[i] = 0x22
	}
	if m.Height != 0 {
		i = encodeVarintAttestation(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x18
	}
	if len(m.Votes) > 0 {
		for iNdEx := len(m.Votes) - 1; iNdEx >= 0; iNdEx-- {
			i -= len(m.Votes[iNdEx])
			copy(dAtA[i:], m.Votes[iNdEx])
			i = encodeVarintAttestation(dAtA, i, uint64(len(m.Votes[iNdEx])))
			i--
			dAtA[i] = 0x12
		}
	}
	if m.Observed {
		i--
		if m.Observed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintAttestation(dAtA []byte, offset int, v uint64) int {
	offset -= sovAttestation(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *Attestation) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Observed {
		n += 2
	}
	if len(m.Votes) > 0 {
		for _, s := range m.Votes {
			l = len(s)
			n += 1 + l + sovAttestation(uint64(l))
		}
	}
	if m.Height != 0 {
		n += 1 + sovAttestation(uint64(m.Height))
	}
	if m.Proposal != nil {
		l = m.Proposal.Size()
		n += 1 + l + sovAttestation(uint64(l))
	}
	return n
}

func sovAttestation(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozAttestation(x uint64) (n int) {
	return sovAttestation(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *Attestation) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowAttestation
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Attestation: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Attestation: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Observed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.Observed = bool(v != 0)
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Votes", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthAttestation
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthAttestation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Votes = append(m.Votes, string(dAtA[iNdEx:postIndex]))
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Proposal", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthAttestation
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthAttestation
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if m.Proposal == nil {
				m.Proposal = &any.Any{}
			}
			if err := m.Proposal.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipAttestation(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthAttestation
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipAttestation(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowAttestation
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowAttestation
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthAttestation
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupAttestation
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthAttestation
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthAttestation        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowAttestation          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupAttestation = fmt.Errorf("proto: unexpected end of group")
)
