// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twilightproject/nyks/forks/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

// QueryParamsRequest is request type for the Query/Params RPC method.
type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0927d5fe8fc4b190, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

// QueryParamsResponse is response type for the Query/Params RPC method.
type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0927d5fe8fc4b190, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryAttestationsRequest struct {
	Limit        uint64 `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	OrderBy      string `protobuf:"bytes,2,opt,name=order_by,json=orderBy,proto3" json:"order_by,omitempty"`
	ProposalType string `protobuf:"bytes,3,opt,name=proposal_type,json=proposalType,proto3" json:"proposal_type,omitempty"`
	BtcHeight    uint64 `protobuf:"varint,4,opt,name=btc_height,json=btcHeight,proto3" json:"btc_height,omitempty"`
}

func (m *QueryAttestationsRequest) Reset()         { *m = QueryAttestationsRequest{} }
func (m *QueryAttestationsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryAttestationsRequest) ProtoMessage()    {}
func (*QueryAttestationsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0927d5fe8fc4b190, []int{2}
}
func (m *QueryAttestationsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestationsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestationsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestationsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestationsRequest.Merge(m, src)
}
func (m *QueryAttestationsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestationsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestationsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestationsRequest proto.InternalMessageInfo

func (m *QueryAttestationsRequest) GetLimit() uint64 {
	if m != nil {
		return m.Limit
	}
	return 0
}

func (m *QueryAttestationsRequest) GetOrderBy() string {
	if m != nil {
		return m.OrderBy
	}
	return ""
}

func (m *QueryAttestationsRequest) GetProposalType() string {
	if m != nil {
		return m.ProposalType
	}
	return ""
}

func (m *QueryAttestationsRequest) GetBtcHeight() uint64 {
	if m != nil {
		return m.BtcHeight
	}
	return 0
}

type QueryAttestationsResponse struct {
	Attestations []Attestation `protobuf:"bytes,1,rep,name=attestations,proto3" json:"attestations"`
}

func (m *QueryAttestationsResponse) Reset()         { *m = QueryAttestationsResponse{} }
func (m *QueryAttestationsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryAttestationsResponse) ProtoMessage()    {}
func (*QueryAttestationsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0927d5fe8fc4b190, []int{3}
}
func (m *QueryAttestationsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryAttestationsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryAttestationsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryAttestationsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryAttestationsResponse.Merge(m, src)
}
func (m *QueryAttestationsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryAttestationsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryAttestationsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryAttestationsResponse proto.InternalMessageInfo

func (m *QueryAttestationsResponse) GetAttestations() []Attestation {
	if m != nil {
		return m.Attestations
	}
	return nil
}

type QueryDelegateKeysByBtcOracleAddressRequest struct {
	BtcOracleAddress string `protobuf:"bytes,1,opt,name=btcOracleAddress,proto3" json:"btcOracleAddress,omitempty"`
}

func (m *QueryDelegateKeysByBtcOracleAddressRequest) Reset() {
	*m = QueryDelegateKeysByBtcOracleAddressRequest{}
}
func (m *QueryDelegateKeysByBtcOracleAddressRequest) String() string {
	return proto.CompactTextString(m)
}
func (*QueryDelegateKeysByBtcOracleAddressRequest) ProtoMessage() {}
func (*QueryDelegateKeysByBtcOracleAddressRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0927d5fe8fc4b190, []int{4}
}
func (m *QueryDelegateKeysByBtcOracleAddressRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDelegateKeysByBtcOracleAddressRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDelegateKeysByBtcOracleAddressRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDelegateKeysByBtcOracleAddressRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDelegateKeysByBtcOracleAddressRequest.Merge(m, src)
}
func (m *QueryDelegateKeysByBtcOracleAddressRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDelegateKeysByBtcOracleAddressRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDelegateKeysByBtcOracleAddressRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDelegateKeysByBtcOracleAddressRequest proto.InternalMessageInfo

func (m *QueryDelegateKeysByBtcOracleAddressRequest) GetBtcOracleAddress() string {
	if m != nil {
		return m.BtcOracleAddress
	}
	return ""
}

type QueryDelegateKeysByBtcOracleAddressResponse struct {
	Addresses MsgSetDelegateAddresses `protobuf:"bytes,1,opt,name=addresses,proto3" json:"addresses"`
}

func (m *QueryDelegateKeysByBtcOracleAddressResponse) Reset() {
	*m = QueryDelegateKeysByBtcOracleAddressResponse{}
}
func (m *QueryDelegateKeysByBtcOracleAddressResponse) String() string {
	return proto.CompactTextString(m)
}
func (*QueryDelegateKeysByBtcOracleAddressResponse) ProtoMessage() {}
func (*QueryDelegateKeysByBtcOracleAddressResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0927d5fe8fc4b190, []int{5}
}
func (m *QueryDelegateKeysByBtcOracleAddressResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDelegateKeysByBtcOracleAddressResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDelegateKeysByBtcOracleAddressResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDelegateKeysByBtcOracleAddressResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDelegateKeysByBtcOracleAddressResponse.Merge(m, src)
}
func (m *QueryDelegateKeysByBtcOracleAddressResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDelegateKeysByBtcOracleAddressResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDelegateKeysByBtcOracleAddressResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDelegateKeysByBtcOracleAddressResponse proto.InternalMessageInfo

func (m *QueryDelegateKeysByBtcOracleAddressResponse) GetAddresses() MsgSetDelegateAddresses {
	if m != nil {
		return m.Addresses
	}
	return MsgSetDelegateAddresses{}
}

type QueryDelegateKeysAllRequest struct {
}

func (m *QueryDelegateKeysAllRequest) Reset()         { *m = QueryDelegateKeysAllRequest{} }
func (m *QueryDelegateKeysAllRequest) String() string { return proto.CompactTextString(m) }
func (*QueryDelegateKeysAllRequest) ProtoMessage()    {}
func (*QueryDelegateKeysAllRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_0927d5fe8fc4b190, []int{6}
}
func (m *QueryDelegateKeysAllRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDelegateKeysAllRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDelegateKeysAllRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDelegateKeysAllRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDelegateKeysAllRequest.Merge(m, src)
}
func (m *QueryDelegateKeysAllRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryDelegateKeysAllRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDelegateKeysAllRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDelegateKeysAllRequest proto.InternalMessageInfo

type QueryDelegateKeysAllResponse struct {
	Addresses []MsgSetDelegateAddresses `protobuf:"bytes,1,rep,name=addresses,proto3" json:"addresses"`
}

func (m *QueryDelegateKeysAllResponse) Reset()         { *m = QueryDelegateKeysAllResponse{} }
func (m *QueryDelegateKeysAllResponse) String() string { return proto.CompactTextString(m) }
func (*QueryDelegateKeysAllResponse) ProtoMessage()    {}
func (*QueryDelegateKeysAllResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_0927d5fe8fc4b190, []int{7}
}
func (m *QueryDelegateKeysAllResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryDelegateKeysAllResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryDelegateKeysAllResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryDelegateKeysAllResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryDelegateKeysAllResponse.Merge(m, src)
}
func (m *QueryDelegateKeysAllResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryDelegateKeysAllResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryDelegateKeysAllResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryDelegateKeysAllResponse proto.InternalMessageInfo

func (m *QueryDelegateKeysAllResponse) GetAddresses() []MsgSetDelegateAddresses {
	if m != nil {
		return m.Addresses
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "twilightproject.nyks.forks.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "twilightproject.nyks.forks.QueryParamsResponse")
	proto.RegisterType((*QueryAttestationsRequest)(nil), "twilightproject.nyks.forks.QueryAttestationsRequest")
	proto.RegisterType((*QueryAttestationsResponse)(nil), "twilightproject.nyks.forks.QueryAttestationsResponse")
	proto.RegisterType((*QueryDelegateKeysByBtcOracleAddressRequest)(nil), "twilightproject.nyks.forks.QueryDelegateKeysByBtcOracleAddressRequest")
	proto.RegisterType((*QueryDelegateKeysByBtcOracleAddressResponse)(nil), "twilightproject.nyks.forks.QueryDelegateKeysByBtcOracleAddressResponse")
	proto.RegisterType((*QueryDelegateKeysAllRequest)(nil), "twilightproject.nyks.forks.QueryDelegateKeysAllRequest")
	proto.RegisterType((*QueryDelegateKeysAllResponse)(nil), "twilightproject.nyks.forks.QueryDelegateKeysAllResponse")
}

func init() {
	proto.RegisterFile("twilightproject/nyks/forks/query.proto", fileDescriptor_0927d5fe8fc4b190)
}

var fileDescriptor_0927d5fe8fc4b190 = []byte{
	// 669 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x55, 0x4f, 0x4f, 0xd4, 0x40,
	0x14, 0xdf, 0xe1, 0xcf, 0xea, 0x0e, 0x18, 0x74, 0xe4, 0xb0, 0x54, 0xa8, 0xd8, 0x4d, 0x64, 0x5d,
	0xb5, 0x25, 0xe0, 0xbf, 0x8b, 0x87, 0xdd, 0xa8, 0x98, 0x18, 0xa3, 0x14, 0x8d, 0x46, 0x4d, 0x9a,
	0xe9, 0xee, 0x58, 0x2a, 0xa5, 0x53, 0x3a, 0x43, 0xa0, 0x31, 0x5e, 0x3c, 0x78, 0x54, 0x13, 0xfd,
	0x02, 0xde, 0x3c, 0xf2, 0x01, 0xfc, 0x00, 0x1c, 0x49, 0xbc, 0x78, 0x32, 0x06, 0x4c, 0xfc, 0x1a,
	0xa6, 0xd3, 0x29, 0x2c, 0xbb, 0xa5, 0xb0, 0xd1, 0x4b, 0xd3, 0xbe, 0xf9, 0xbd, 0xdf, 0xfb, 0xfd,
	0x5e, 0xdf, 0x6b, 0xe1, 0x79, 0xbe, 0xe6, 0x7a, 0xae, 0xb3, 0xc8, 0x83, 0x90, 0xbe, 0x22, 0x4d,
	0x6e, 0xf8, 0xd1, 0x12, 0x33, 0x5e, 0xd2, 0x70, 0x89, 0x19, 0x2b, 0xab, 0x24, 0x8c, 0xf4, 0x20,
	0xa4, 0x9c, 0x22, 0xa5, 0x03, 0xa7, 0xc7, 0x38, 0x5d, 0xe0, 0x94, 0x53, 0x78, 0xd9, 0xf5, 0xa9,
	0x21, 0xae, 0x09, 0x5c, 0x19, 0x75, 0xa8, 0x43, 0xc5, 0xad, 0x11, 0xdf, 0xc9, 0xe8, 0xb8, 0x43,
	0xa9, 0xe3, 0x11, 0x03, 0x07, 0xae, 0x81, 0x7d, 0x9f, 0x72, 0xcc, 0x5d, 0xea, 0x33, 0x79, 0x3a,
	0x95, 0x23, 0x25, 0xc0, 0x21, 0x5e, 0x4e, 0x81, 0x95, 0x1c, 0x20, 0x5f, 0x97, 0xa0, 0x4b, 0x39,
	0x20, 0xcc, 0x39, 0x61, 0x49, 0xf1, 0x04, 0xad, 0x8d, 0x42, 0x34, 0x1f, 0xbb, 0x7d, 0x28, 0xea,
	0x98, 0x64, 0x65, 0x95, 0x30, 0xae, 0xbd, 0x80, 0xa7, 0xf7, 0x45, 0x59, 0x40, 0x7d, 0x46, 0xd0,
	0x6d, 0x58, 0x4c, 0xf4, 0x94, 0xc1, 0x24, 0xa8, 0x0e, 0xcd, 0x68, 0xfa, 0xc1, 0xcd, 0xd1, 0x93,
	0xdc, 0x46, 0x69, 0xf3, 0xe7, 0xd9, 0xc2, 0xd7, 0x3f, 0x1b, 0x35, 0x60, 0xca, 0x64, 0xed, 0x03,
	0x80, 0x65, 0x41, 0x5f, 0xdf, 0x93, 0x93, 0x96, 0x46, 0xa3, 0x70, 0xd0, 0x73, 0x97, 0x5d, 0x2e,
	0x4a, 0x0c, 0x98, 0xc9, 0x03, 0x1a, 0x83, 0xc7, 0x69, 0xd8, 0x22, 0xa1, 0x65, 0x47, 0xe5, 0xbe,
	0x49, 0x50, 0x2d, 0x99, 0xc7, 0xc4, 0x73, 0x23, 0x42, 0x15, 0x78, 0x22, 0x08, 0x69, 0x40, 0x19,
	0xf6, 0x2c, 0x1e, 0x05, 0xa4, 0xdc, 0x2f, 0xce, 0x87, 0xd3, 0xe0, 0xa3, 0x28, 0x20, 0x68, 0x02,
	0x42, 0x9b, 0x37, 0xad, 0x45, 0x12, 0x8b, 0x2d, 0x0f, 0x08, 0xea, 0x92, 0xcd, 0x9b, 0x77, 0x45,
	0x40, 0xf3, 0xe1, 0x58, 0x86, 0x20, 0xe9, 0x7a, 0x1e, 0x0e, 0xb7, 0xf5, 0x2d, 0xf6, 0xde, 0x5f,
	0x1d, 0x9a, 0x99, 0xca, 0xf3, 0xde, 0xc6, 0xd3, 0x18, 0x88, 0x1b, 0x60, 0xee, 0xa3, 0xd0, 0x9e,
	0xc2, 0x9a, 0xa8, 0x77, 0x8b, 0x78, 0xc4, 0xc1, 0x9c, 0xdc, 0x23, 0x11, 0x6b, 0x44, 0x0d, 0xde,
	0x7c, 0x10, 0xe2, 0xa6, 0x47, 0xea, 0xad, 0x56, 0x48, 0xd8, 0x6e, 0x4b, 0x6a, 0xf0, 0xa4, 0xdd,
	0x71, 0x24, 0xba, 0x53, 0x32, 0xbb, 0xe2, 0xda, 0x3b, 0x00, 0x2f, 0x1e, 0x89, 0x5a, 0x9a, 0x7b,
	0x02, 0x4b, 0x38, 0x09, 0x91, 0xf4, 0xad, 0xce, 0xe6, 0x39, 0xbb, 0xcf, 0x9c, 0x05, 0xc2, 0x53,
	0xf2, 0x7a, 0x9a, 0x2a, 0x5d, 0xee, 0x71, 0x69, 0x13, 0xf0, 0x4c, 0x97, 0x8e, 0xba, 0xe7, 0xa5,
	0x13, 0xb6, 0x06, 0xc7, 0xb3, 0x8f, 0xb3, 0x75, 0xf5, 0xff, 0x2f, 0x5d, 0x33, 0x5f, 0x8a, 0x70,
	0x50, 0x54, 0x46, 0x9f, 0x01, 0x2c, 0x26, 0x43, 0x8a, 0xf4, 0x3c, 0xea, 0xee, 0xfd, 0x50, 0x8c,
	0x23, 0xe3, 0x13, 0x3b, 0xda, 0x85, 0xb7, 0xdf, 0x7f, 0x7f, 0xea, 0xab, 0xa0, 0x73, 0x46, 0xe6,
	0x76, 0x8a, 0x4b, 0xb2, 0x1d, 0x68, 0x03, 0xc0, 0x91, 0x39, 0xc2, 0xdb, 0x47, 0x11, 0x5d, 0x39,
	0xb4, 0x5e, 0xc6, 0x2a, 0x29, 0x57, 0x7b, 0xcc, 0x92, 0x5a, 0xa7, 0x85, 0xd6, 0x1a, 0xaa, 0xee,
	0x6a, 0xbd, 0xdc, 0x2d, 0xb6, 0x7d, 0x9c, 0xd1, 0xfb, 0x3e, 0xa8, 0xe6, 0xcf, 0x1b, 0xba, 0x73,
	0xa8, 0x96, 0x23, 0xed, 0x82, 0x32, 0xf7, 0xcf, 0x3c, 0xd2, 0xe5, 0x73, 0xe1, 0xf2, 0x31, 0x5a,
	0x38, 0xc0, 0x65, 0xf2, 0xc1, 0x6c, 0x49, 0x32, 0x6b, 0x89, 0x44, 0xcc, 0xb2, 0x23, 0x2b, 0xfe,
	0x8a, 0x50, 0x41, 0x68, 0xc9, 0x99, 0x32, 0x5e, 0x77, 0x2e, 0xe1, 0x1b, 0xf4, 0x0d, 0xc0, 0x91,
	0x8e, 0xc9, 0x46, 0xd7, 0x7b, 0x52, 0xbe, 0xb7, 0x2a, 0xca, 0x8d, 0xde, 0x13, 0xa5, 0xc7, 0x6b,
	0xc2, 0xe3, 0x34, 0xd2, 0x7b, 0xf0, 0x88, 0x3d, 0xaf, 0x71, 0x73, 0x73, 0x5b, 0x05, 0x5b, 0xdb,
	0x2a, 0xf8, 0xb5, 0xad, 0x82, 0x8f, 0x3b, 0x6a, 0x61, 0x6b, 0x47, 0x2d, 0xfc, 0xd8, 0x51, 0x0b,
	0xcf, 0x2a, 0xd9, 0x44, 0xeb, 0xe9, 0x4f, 0x28, 0x0a, 0x08, 0xb3, 0x8b, 0xe2, 0xd7, 0x32, 0xfb,
	0x37, 0x00, 0x00, 0xff, 0xff, 0xa2, 0xf8, 0x83, 0xde, 0x63, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	// Parameters queries the parameters of the module.
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	// GetAttestations queries attestations with optional filters.
	GetAttestations(ctx context.Context, in *QueryAttestationsRequest, opts ...grpc.CallOption) (*QueryAttestationsResponse, error)
	// DelegateKeysByBtcOracleAddress queries delegate keys by btc oracle address.
	DelegateKeysByBtcOracleAddress(ctx context.Context, in *QueryDelegateKeysByBtcOracleAddressRequest, opts ...grpc.CallOption) (*QueryDelegateKeysByBtcOracleAddressResponse, error)
	// DelegateKeysAll queries all delegate keys.
	DelegateKeysAll(ctx context.Context, in *QueryDelegateKeysAllRequest, opts ...grpc.CallOption) (*QueryDelegateKeysAllResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.forks.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) GetAttestations(ctx context.Context, in *QueryAttestationsRequest, opts ...grpc.CallOption) (*QueryAttestationsResponse, error) {
	out := new(QueryAttestationsResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.forks.Query/GetAttestations", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DelegateKeysByBtcOracleAddress(ctx context.Context, in *QueryDelegateKeysByBtcOracleAddressRequest, opts ...grpc.CallOption) (*QueryDelegateKeysByBtcOracleAddressResponse, error) {
	out := new(QueryDelegateKeysByBtcOracleAddressResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.forks.Query/DelegateKeysByBtcOracleAddress", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) DelegateKeysAll(ctx context.Context, in *QueryDelegateKeysAllRequest, opts ...grpc.CallOption) (*QueryDelegateKeysAllResponse, error) {
	out := new(QueryDelegateKeysAllResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.forks.Query/DelegateKeysAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	// Parameters queries the parameters of the module.
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	// GetAttestations queries attestations with optional filters.
	GetAttestations(context.Context, *QueryAttestationsRequest) (*QueryAttestationsResponse, error)
	// DelegateKeysByBtcOracleAddress queries delegate keys by btc oracle address.
	DelegateKeysByBtcOracleAddress(context.Context, *QueryDelegateKeysByBtcOracleAddressRequest) (*QueryDelegateKeysByBtcOracleAddressResponse, error)
	// DelegateKeysAll queries all delegate keys.
	DelegateKeysAll(context.Context, *QueryDelegateKeysAllRequest) (*QueryDelegateKeysAllResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) GetAttestations(ctx context.Context, req *QueryAttestationsRequest) (*QueryAttestationsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetAttestations not implemented")
}
func (*UnimplementedQueryServer) DelegateKeysByBtcOracleAddress(ctx context.Context, req *QueryDelegateKeysByBtcOracleAddressRequest) (*QueryDelegateKeysByBtcOracleAddressResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegateKeysByBtcOracleAddress not implemented")
}
func (*UnimplementedQueryServer) DelegateKeysAll(ctx context.Context, req *QueryDelegateKeysAllRequest) (*QueryDelegateKeysAllResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelegateKeysAll not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.forks.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_GetAttestations_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryAttestationsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).GetAttestations(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.forks.Query/GetAttestations",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).GetAttestations(ctx, req.(*QueryAttestationsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DelegateKeysByBtcOracleAddress_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDelegateKeysByBtcOracleAddressRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DelegateKeysByBtcOracleAddress(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.forks.Query/DelegateKeysByBtcOracleAddress",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DelegateKeysByBtcOracleAddress(ctx, req.(*QueryDelegateKeysByBtcOracleAddressRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_DelegateKeysAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryDelegateKeysAllRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DelegateKeysAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.forks.Query/DelegateKeysAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DelegateKeysAll(ctx, req.(*QueryDelegateKeysAllRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twilightproject.nyks.forks.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "GetAttestations",
			Handler:    _Query_GetAttestations_Handler,
		},
		{
			MethodName: "DelegateKeysByBtcOracleAddress",
			Handler:    _Query_DelegateKeysByBtcOracleAddress_Handler,
		},
		{
			MethodName: "DelegateKeysAll",
			Handler:    _Query_DelegateKeysAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twilightproject/nyks/forks/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryAttestationsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestationsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestationsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BtcHeight != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.BtcHeight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.ProposalType) > 0 {
		i -= len(m.ProposalType)
		copy(dAtA[i:], m.ProposalType)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.ProposalType)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.OrderBy) > 0 {
		i -= len(m.OrderBy)
		copy(dAtA[i:], m.OrderBy)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.OrderBy)))
		i--
		dAtA[i] = 0x12
	}
	if m.Limit != 0 {
		i = encodeVarintQuery(dAtA, i, uint64(m.Limit))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *QueryAttestationsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryAttestationsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryAttestationsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Attestations) > 0 {
		for iNdEx := len(m.Attestations) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Attestations[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func (m *QueryDelegateKeysByBtcOracleAddressRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDelegateKeysByBtcOracleAddressRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDelegateKeysByBtcOracleAddressRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BtcOracleAddress) > 0 {
		i -= len(m.BtcOracleAddress)
		copy(dAtA[i:], m.BtcOracleAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.BtcOracleAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryDelegateKeysByBtcOracleAddressResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDelegateKeysByBtcOracleAddressResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDelegateKeysByBtcOracleAddressResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Addresses.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryDelegateKeysAllRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDelegateKeysAllRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDelegateKeysAllRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryDelegateKeysAllResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryDelegateKeysAllResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryDelegateKeysAllResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for iNdEx := len(m.Addresses) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Addresses[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryAttestationsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Limit != 0 {
		n += 1 + sovQuery(uint64(m.Limit))
	}
	l = len(m.OrderBy)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	l = len(m.ProposalType)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	if m.BtcHeight != 0 {
		n += 1 + sovQuery(uint64(m.BtcHeight))
	}
	return n
}

func (m *QueryAttestationsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Attestations) > 0 {
		for _, e := range m.Attestations {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func (m *QueryDelegateKeysByBtcOracleAddressRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BtcOracleAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryDelegateKeysByBtcOracleAddressResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Addresses.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryDelegateKeysAllRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryDelegateKeysAllResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.Addresses) > 0 {
		for _, e := range m.Addresses {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAttestationsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestationsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestationsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Limit", wireType)
			}
			m.Limit = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Limit |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field OrderBy", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.OrderBy = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ProposalType", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ProposalType = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcHeight", wireType)
			}
			m.BtcHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BtcHeight |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryAttestationsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryAttestationsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryAttestationsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Attestations", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Attestations = append(m.Attestations, Attestation{})
			if err := m.Attestations[len(m.Attestations)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDelegateKeysByBtcOracleAddressRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDelegateKeysByBtcOracleAddressRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDelegateKeysByBtcOracleAddressRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcOracleAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcOracleAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDelegateKeysByBtcOracleAddressResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDelegateKeysByBtcOracleAddressResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDelegateKeysByBtcOracleAddressResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Addresses.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDelegateKeysAllRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDelegateKeysAllRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDelegateKeysAllRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryDelegateKeysAllResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryDelegateKeysAllResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryDelegateKeysAllResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Addresses", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Addresses = append(m.Addresses, MsgSetDelegateAddresses{})
			if err := m.Addresses[len(m.Addresses)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
