// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twilightproject/nyks/forks/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_6809e4684cb3738a, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6809e4684cb3738a, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgSetDelegateAddresses struct {
	ValidatorAddress string `protobuf:"bytes,1,opt,name=validatorAddress,proto3" json:"validatorAddress,omitempty"`
	BtcOracleAddress string `protobuf:"bytes,2,opt,name=btcOracleAddress,proto3" json:"btcOracleAddress,omitempty"`
	BtcPublicKey     string `protobuf:"bytes,3,opt,name=btcPublicKey,proto3" json:"btcPublicKey,omitempty"`
	ZkOracleAddress  string `protobuf:"bytes,4,opt,name=zkOracleAddress,proto3" json:"zkOracleAddress,omitempty"`
}

func (m *MsgSetDelegateAddresses) Reset()         { *m = MsgSetDelegateAddresses{} }
func (m *MsgSetDelegateAddresses) String() string { return proto.CompactTextString(m) }
func (*MsgSetDelegateAddresses) ProtoMessage()    {}
func (*MsgSetDelegateAddresses) Descriptor() ([]byte, []int) {
	return fileDescriptor_6809e4684cb3738a, []int{2}
}
func (m *MsgSetDelegateAddresses) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetDelegateAddresses) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetDelegateAddresses.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetDelegateAddresses) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetDelegateAddresses.Merge(m, src)
}
func (m *MsgSetDelegateAddresses) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetDelegateAddresses) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetDelegateAddresses.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetDelegateAddresses proto.InternalMessageInfo

func (m *MsgSetDelegateAddresses) GetValidatorAddress() string {
	if m != nil {
		return m.ValidatorAddress
	}
	return ""
}

func (m *MsgSetDelegateAddresses) GetBtcOracleAddress() string {
	if m != nil {
		return m.BtcOracleAddress
	}
	return ""
}

func (m *MsgSetDelegateAddresses) GetBtcPublicKey() string {
	if m != nil {
		return m.BtcPublicKey
	}
	return ""
}

func (m *MsgSetDelegateAddresses) GetZkOracleAddress() string {
	if m != nil {
		return m.ZkOracleAddress
	}
	return ""
}

type MsgSetDelegateAddressesResponse struct {
	Id uint64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (m *MsgSetDelegateAddressesResponse) Reset()         { *m = MsgSetDelegateAddressesResponse{} }
func (m *MsgSetDelegateAddressesResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSetDelegateAddressesResponse) ProtoMessage()    {}
func (*MsgSetDelegateAddressesResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6809e4684cb3738a, []int{3}
}
func (m *MsgSetDelegateAddressesResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSetDelegateAddressesResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSetDelegateAddressesResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSetDelegateAddressesResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSetDelegateAddressesResponse.Merge(m, src)
}
func (m *MsgSetDelegateAddressesResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSetDelegateAddressesResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSetDelegateAddressesResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSetDelegateAddressesResponse proto.InternalMessageInfo

func (m *MsgSetDelegateAddressesResponse) GetId() uint64 {
	if m != nil {
		return m.Id
	}
	return 0
}

type MsgSeenBtcChainTip struct {
	Height           uint64 `protobuf:"varint,1,opt,name=height,proto3" json:"height,omitempty"`
	Hash             string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
	BtcOracleAddress string `protobuf:"bytes,3,opt,name=btcOracleAddress,proto3" json:"btcOracleAddress,omitempty"`
}

func (m *MsgSeenBtcChainTip) Reset()         { *m = MsgSeenBtcChainTip{} }
func (m *MsgSeenBtcChainTip) String() string { return proto.CompactTextString(m) }
func (*MsgSeenBtcChainTip) ProtoMessage()    {}
func (*MsgSeenBtcChainTip) Descriptor() ([]byte, []int) {
	return fileDescriptor_6809e4684cb3738a, []int{4}
}
func (m *MsgSeenBtcChainTip) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSeenBtcChainTip) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSeenBtcChainTip.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSeenBtcChainTip) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSeenBtcChainTip.Merge(m, src)
}
func (m *MsgSeenBtcChainTip) XXX_Size() int {
	return m.Size()
}
func (m *MsgSeenBtcChainTip) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSeenBtcChainTip.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSeenBtcChainTip proto.InternalMessageInfo

func (m *MsgSeenBtcChainTip) GetHeight() uint64 {
	if m != nil {
		return m.Height
	}
	return 0
}

func (m *MsgSeenBtcChainTip) GetHash() string {
	if m != nil {
		return m.Hash
	}
	return ""
}

func (m *MsgSeenBtcChainTip) GetBtcOracleAddress() string {
	if m != nil {
		return m.BtcOracleAddress
	}
	return ""
}

type MsgSeenBtcChainTipResponse struct {
}

func (m *MsgSeenBtcChainTipResponse) Reset()         { *m = MsgSeenBtcChainTipResponse{} }
func (m *MsgSeenBtcChainTipResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSeenBtcChainTipResponse) ProtoMessage()    {}
func (*MsgSeenBtcChainTipResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_6809e4684cb3738a, []int{5}
}
func (m *MsgSeenBtcChainTipResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSeenBtcChainTipResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSeenBtcChainTipResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSeenBtcChainTipResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSeenBtcChainTipResponse.Merge(m, src)
}
func (m *MsgSeenBtcChainTipResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSeenBtcChainTipResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSeenBtcChainTipResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSeenBtcChainTipResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "twilightproject.nyks.forks.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "twilightproject.nyks.forks.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgSetDelegateAddresses)(nil), "twilightproject.nyks.forks.MsgSetDelegateAddresses")
	proto.RegisterType((*MsgSetDelegateAddressesResponse)(nil), "twilightproject.nyks.forks.MsgSetDelegateAddressesResponse")
	proto.RegisterType((*MsgSeenBtcChainTip)(nil), "twilightproject.nyks.forks.MsgSeenBtcChainTip")
	proto.RegisterType((*MsgSeenBtcChainTipResponse)(nil), "twilightproject.nyks.forks.MsgSeenBtcChainTipResponse")
}

func init() {
	proto.RegisterFile("twilightproject/nyks/forks/tx.proto", fileDescriptor_6809e4684cb3738a)
}

var fileDescriptor_6809e4684cb3738a = []byte{
	// 558 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x3f, 0x6f, 0xd3, 0x4e,
	0x18, 0xce, 0x25, 0xf9, 0x45, 0xca, 0xfd, 0x2a, 0x02, 0xa7, 0x40, 0x53, 0xab, 0x72, 0x2b, 0x33,
	0x10, 0x05, 0xd5, 0x56, 0x5b, 0xa9, 0x43, 0x11, 0x03, 0x01, 0x26, 0x54, 0x51, 0xb9, 0xb0, 0xb0,
	0xa0, 0x8b, 0x7d, 0xd8, 0x47, 0x12, 0x9f, 0xe5, 0xbb, 0x96, 0x9a, 0x09, 0x01, 0x03, 0x62, 0xe2,
	0x63, 0x30, 0x66, 0xe0, 0x0b, 0xb0, 0x75, 0xac, 0x18, 0x10, 0x13, 0x42, 0xc9, 0x90, 0xaf, 0x81,
	0x7c, 0x3e, 0xa7, 0xb2, 0x93, 0xb6, 0x2a, 0x8b, 0x7d, 0xf7, 0xbc, 0xcf, 0xfb, 0xde, 0xf3, 0xbc,
	0xf7, 0x07, 0xde, 0x16, 0x6f, 0xe8, 0x80, 0x7a, 0xbe, 0x08, 0x23, 0xf6, 0x9a, 0x38, 0xc2, 0x0a,
	0xe2, 0x3e, 0xb7, 0x5e, 0xb1, 0xa8, 0xcf, 0x2d, 0x71, 0x6c, 0x86, 0x11, 0x13, 0x0c, 0x69, 0x05,
	0x92, 0x99, 0x90, 0x4c, 0x49, 0xd2, 0x6e, 0xe0, 0x21, 0x0d, 0x98, 0x25, 0xbf, 0x29, 0x5d, 0x5b,
	0x76, 0x18, 0x1f, 0x32, 0x6e, 0x0d, 0xb9, 0x67, 0x1d, 0x6d, 0x26, 0x3f, 0x15, 0x58, 0x49, 0x03,
	0x2f, 0xe5, 0xcc, 0x4a, 0x27, 0x2a, 0xd4, 0xf4, 0x98, 0xc7, 0x52, 0x3c, 0x19, 0x29, 0xf4, 0xce,
	0x05, 0xea, 0x42, 0x1c, 0xe1, 0xa1, 0x4a, 0x37, 0xbe, 0x03, 0xd8, 0xd8, 0xe3, 0xde, 0xf3, 0xd0,
	0xc5, 0x82, 0xec, 0xcb, 0x08, 0xda, 0x81, 0x75, 0x7c, 0x28, 0x7c, 0x16, 0x51, 0x11, 0xb7, 0xc0,
	0x3a, 0x68, 0xd7, 0xbb, 0xad, 0x1f, 0xdf, 0x36, 0x9a, 0x6a, 0xdd, 0x07, 0xae, 0x1b, 0x11, 0xce,
	0x0f, 0x44, 0x44, 0x03, 0xcf, 0x3e, 0xa3, 0xa2, 0xc7, 0xb0, 0x96, 0xd6, 0x6e, 0x95, 0xd7, 0x41,
	0xfb, 0xff, 0x2d, 0xc3, 0x3c, 0xdf, 0xbe, 0x99, 0xae, 0xd5, 0xad, 0x9f, 0xfc, 0x5e, 0x2b, 0x7d,
	0x9d, 0x8e, 0x3a, 0xc0, 0x56, 0xc9, 0xbb, 0xd6, 0xfb, 0xe9, 0xa8, 0x73, 0x56, 0xf6, 0xf3, 0x74,
	0xd4, 0x59, 0x95, 0xf2, 0x8f, 0x95, 0x81, 0x82, 0x5e, 0x63, 0x05, 0x2e, 0x17, 0x20, 0x9b, 0xf0,
	0x90, 0x05, 0x9c, 0x18, 0x3f, 0x81, 0x8c, 0x1d, 0x10, 0xf1, 0x88, 0x0c, 0x88, 0x87, 0x05, 0x51,
	0xea, 0x09, 0x47, 0x1d, 0x78, 0xfd, 0x08, 0x0f, 0xa8, 0x8b, 0x05, 0x8b, 0x14, 0x9a, 0xba, 0xb5,
	0xe7, 0xf0, 0x84, 0xdb, 0x13, 0xce, 0xd3, 0x08, 0x3b, 0x83, 0xac, 0x82, 0x34, 0x59, 0xb7, 0xe7,
	0x70, 0x64, 0xc0, 0xa5, 0x9e, 0x70, 0xf6, 0x0f, 0x7b, 0x03, 0xea, 0x3c, 0x21, 0x71, 0xab, 0x22,
	0x79, 0x39, 0x0c, 0xb5, 0x61, 0xe3, 0x6d, 0x3f, 0x5f, 0xae, 0x2a, 0x69, 0x45, 0x78, 0xf7, 0x66,
	0xd2, 0x8d, 0x39, 0x41, 0xc6, 0x26, 0x5c, 0x3b, 0xc7, 0x57, 0xe6, 0x1d, 0x5d, 0x83, 0x65, 0xea,
	0x4a, 0x47, 0x55, 0xbb, 0x4c, 0x5d, 0xe3, 0x03, 0x80, 0x48, 0xe6, 0x90, 0xa0, 0x2b, 0x9c, 0x87,
	0x3e, 0xa6, 0xc1, 0x33, 0x1a, 0xa2, 0x5b, 0xb0, 0xe6, 0x93, 0x64, 0x93, 0x14, 0x55, 0xcd, 0x10,
	0x82, 0x55, 0x1f, 0x73, 0x5f, 0xd9, 0x94, 0xe3, 0x85, 0x6d, 0xa8, 0x2c, 0x6e, 0x83, 0x12, 0x5e,
	0x84, 0x8d, 0x55, 0xa8, 0xcd, 0x8b, 0xc8, 0x34, 0x6f, 0x7d, 0xac, 0xc0, 0xca, 0x1e, 0xf7, 0x50,
	0x08, 0x97, 0x72, 0x47, 0xf2, 0xee, 0x45, 0x47, 0xa9, 0xb0, 0xf9, 0xda, 0xf6, 0x15, 0xc8, 0xb3,
	0x6e, 0x7d, 0x02, 0xb0, 0xb9, 0xf0, 0x98, 0x5c, 0x56, 0x6d, 0x51, 0x92, 0x76, 0xef, 0x1f, 0x92,
	0x66, 0x52, 0x62, 0xd8, 0x28, 0x6e, 0x92, 0x79, 0x69, 0xbd, 0x1c, 0x5f, 0xdb, 0xb9, 0x1a, 0x3f,
	0x5b, 0x5a, 0xfb, 0xef, 0x5d, 0x72, 0x15, 0xbb, 0xf7, 0x4f, 0xc6, 0x3a, 0x38, 0x1d, 0xeb, 0xe0,
	0xcf, 0x58, 0x07, 0x5f, 0x26, 0x7a, 0xe9, 0x74, 0xa2, 0x97, 0x7e, 0x4d, 0xf4, 0xd2, 0x8b, 0xd9,
	0xb3, 0xb7, 0x91, 0x7b, 0x59, 0xb2, 0xab, 0x29, 0xe2, 0x90, 0xf0, 0x5e, 0x4d, 0xbe, 0x2d, 0xdb,
	0x7f, 0x03, 0x00, 0x00, 0xff, 0xff, 0x96, 0x4d, 0xbe, 0x31, 0x24, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	SetDelegateAddresses(ctx context.Context, in *MsgSetDelegateAddresses, opts ...grpc.CallOption) (*MsgSetDelegateAddressesResponse, error)
	SeenBtcChainTip(ctx context.Context, in *MsgSeenBtcChainTip, opts ...grpc.CallOption) (*MsgSeenBtcChainTipResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.forks.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SetDelegateAddresses(ctx context.Context, in *MsgSetDelegateAddresses, opts ...grpc.CallOption) (*MsgSetDelegateAddressesResponse, error) {
	out := new(MsgSetDelegateAddressesResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.forks.Msg/SetDelegateAddresses", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SeenBtcChainTip(ctx context.Context, in *MsgSeenBtcChainTip, opts ...grpc.CallOption) (*MsgSeenBtcChainTipResponse, error) {
	out := new(MsgSeenBtcChainTipResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.forks.Msg/SeenBtcChainTip", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	SetDelegateAddresses(context.Context, *MsgSetDelegateAddresses) (*MsgSetDelegateAddressesResponse, error)
	SeenBtcChainTip(context.Context, *MsgSeenBtcChainTip) (*MsgSeenBtcChainTipResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) SetDelegateAddresses(ctx context.Context, req *MsgSetDelegateAddresses) (*MsgSetDelegateAddressesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetDelegateAddresses not implemented")
}
func (*UnimplementedMsgServer) SeenBtcChainTip(ctx context.Context, req *MsgSeenBtcChainTip) (*MsgSeenBtcChainTipResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SeenBtcChainTip not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.forks.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SetDelegateAddresses_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSetDelegateAddresses)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SetDelegateAddresses(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.forks.Msg/SetDelegateAddresses",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SetDelegateAddresses(ctx, req.(*MsgSetDelegateAddresses))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SeenBtcChainTip_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSeenBtcChainTip)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SeenBtcChainTip(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.forks.Msg/SeenBtcChainTip",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SeenBtcChainTip(ctx, req.(*MsgSeenBtcChainTip))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twilightproject.nyks.forks.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "SetDelegateAddresses",
			Handler:    _Msg_SetDelegateAddresses_Handler,
		},
		{
			MethodName: "SeenBtcChainTip",
			Handler:    _Msg_SeenBtcChainTip_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twilightproject/nyks/forks/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSetDelegateAddresses) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetDelegateAddresses) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetDelegateAddresses) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ZkOracleAddress) > 0 {
		i -= len(m.ZkOracleAddress)
		copy(dAtA[i:], m.ZkOracleAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ZkOracleAddress)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.BtcPublicKey) > 0 {
		i -= len(m.BtcPublicKey)
		copy(dAtA[i:], m.BtcPublicKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BtcPublicKey)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.BtcOracleAddress) > 0 {
		i -= len(m.BtcOracleAddress)
		copy(dAtA[i:], m.BtcOracleAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BtcOracleAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.ValidatorAddress) > 0 {
		i -= len(m.ValidatorAddress)
		copy(dAtA[i:], m.ValidatorAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ValidatorAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgSetDelegateAddressesResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSetDelegateAddressesResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSetDelegateAddressesResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Id != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Id))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSeenBtcChainTip) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSeenBtcChainTip) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSeenBtcChainTip) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.BtcOracleAddress) > 0 {
		i -= len(m.BtcOracleAddress)
		copy(dAtA[i:], m.BtcOracleAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BtcOracleAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.Hash) > 0 {
		i -= len(m.Hash)
		copy(dAtA[i:], m.Hash)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Hash)))
		i--
		dAtA[i] = 0x12
	}
	if m.Height != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Height))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSeenBtcChainTipResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSeenBtcChainTipResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSeenBtcChainTipResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSetDelegateAddresses) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.ValidatorAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BtcOracleAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BtcPublicKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.ZkOracleAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSetDelegateAddressesResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Id != 0 {
		n += 1 + sovTx(uint64(m.Id))
	}
	return n
}

func (m *MsgSeenBtcChainTip) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Height != 0 {
		n += 1 + sovTx(uint64(m.Height))
	}
	l = len(m.Hash)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.BtcOracleAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSeenBtcChainTipResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetDelegateAddresses) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetDelegateAddresses: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetDelegateAddresses: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ValidatorAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ValidatorAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcOracleAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcOracleAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZkOracleAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZkOracleAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSetDelegateAddressesResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSetDelegateAddressesResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSetDelegateAddressesResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Id", wireType)
			}
			m.Id = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Id |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSeenBtcChainTip) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSeenBtcChainTip: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSeenBtcChainTip: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Height", wireType)
			}
			m.Height = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Height |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Hash", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Hash = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcOracleAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcOracleAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSeenBtcChainTipResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSeenBtcChainTipResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSeenBtcChainTipResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
