// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twilightproject/nyks/volt/clearing.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type IndividualTwilightReserveAccountBalance struct {
	ReserveId uint64 `protobuf:"varint,1,opt,name=ReserveId,proto3" json:"ReserveId,omitempty"`
	Amount    uint64 `protobuf:"varint,2,opt,name=Amount,proto3" json:"Amount,omitempty"`
}

func (m *IndividualTwilightReserveAccountBalance) Reset() {
	*m = IndividualTwilightReserveAccountBalance{}
}
func (m *IndividualTwilightReserveAccountBalance) String() string { return proto.CompactTextString(m) }
func (*IndividualTwilightReserveAccountBalance) ProtoMessage()    {}
func (*IndividualTwilightReserveAccountBalance) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b8c38580db6c779, []int{0}
}
func (m *IndividualTwilightReserveAccountBalance) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *IndividualTwilightReserveAccountBalance) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_IndividualTwilightReserveAccountBalance.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *IndividualTwilightReserveAccountBalance) XXX_Merge(src proto.Message) {
	xxx_messageInfo_IndividualTwilightReserveAccountBalance.Merge(m, src)
}
func (m *IndividualTwilightReserveAccountBalance) XXX_Size() int {
	return m.Size()
}
func (m *IndividualTwilightReserveAccountBalance) XXX_DiscardUnknown() {
	xxx_messageInfo_IndividualTwilightReserveAccountBalance.DiscardUnknown(m)
}

var xxx_messageInfo_IndividualTwilightReserveAccountBalance proto.InternalMessageInfo

func (m *IndividualTwilightReserveAccountBalance) GetReserveId() uint64 {
	if m != nil {
		return m.ReserveId
	}
	return 0
}

func (m *IndividualTwilightReserveAccountBalance) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

type ClearingAccount struct {
	TwilightAddress              string                                     `protobuf:"bytes,1,opt,name=TwilightAddress,proto3" json:"TwilightAddress,omitempty"`
	BtcDepositAddress            string                                     `protobuf:"bytes,2,opt,name=BtcDepositAddress,proto3" json:"BtcDepositAddress,omitempty"`
	BtcDepositAddressIdentifier  uint32                                     `protobuf:"varint,3,opt,name=BtcDepositAddressIdentifier,proto3" json:"BtcDepositAddressIdentifier,omitempty"`
	BtcWithdrawAddress           string                                     `protobuf:"bytes,4,opt,name=BtcWithdrawAddress,proto3" json:"BtcWithdrawAddress,omitempty"`
	BtcWithdrawAddressIdentifier uint32                                     `protobuf:"varint,5,opt,name=BtcWithdrawAddressIdentifier,proto3" json:"BtcWithdrawAddressIdentifier,omitempty"`
	ReserveAccountBalances       []*IndividualTwilightReserveAccountBalance `protobuf:"bytes,6,rep,name=ReserveAccountBalances,proto3" json:"ReserveAccountBalances,omitempty"`
}

func (m *ClearingAccount) Reset()         { *m = ClearingAccount{} }
func (m *ClearingAccount) String() string { return proto.CompactTextString(m) }
func (*ClearingAccount) ProtoMessage()    {}
func (*ClearingAccount) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b8c38580db6c779, []int{1}
}
func (m *ClearingAccount) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *ClearingAccount) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_ClearingAccount.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *ClearingAccount) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ClearingAccount.Merge(m, src)
}
func (m *ClearingAccount) XXX_Size() int {
	return m.Size()
}
func (m *ClearingAccount) XXX_DiscardUnknown() {
	xxx_messageInfo_ClearingAccount.DiscardUnknown(m)
}

var xxx_messageInfo_ClearingAccount proto.InternalMessageInfo

func (m *ClearingAccount) GetTwilightAddress() string {
	if m != nil {
		return m.TwilightAddress
	}
	return ""
}

func (m *ClearingAccount) GetBtcDepositAddress() string {
	if m != nil {
		return m.BtcDepositAddress
	}
	return ""
}

func (m *ClearingAccount) GetBtcDepositAddressIdentifier() uint32 {
	if m != nil {
		return m.BtcDepositAddressIdentifier
	}
	return 0
}

func (m *ClearingAccount) GetBtcWithdrawAddress() string {
	if m != nil {
		return m.BtcWithdrawAddress
	}
	return ""
}

func (m *ClearingAccount) GetBtcWithdrawAddressIdentifier() uint32 {
	if m != nil {
		return m.BtcWithdrawAddressIdentifier
	}
	return 0
}

func (m *ClearingAccount) GetReserveAccountBalances() []*IndividualTwilightReserveAccountBalance {
	if m != nil {
		return m.ReserveAccountBalances
	}
	return nil
}

type RefundTxAccountSnap struct {
	Amount                      uint64 `protobuf:"varint,1,opt,name=Amount,proto3" json:"Amount,omitempty"`
	BtcDepositAddress           string `protobuf:"bytes,2,opt,name=BtcDepositAddress,proto3" json:"BtcDepositAddress,omitempty"`
	BtcDepositAddressIdentifier uint32 `protobuf:"varint,3,opt,name=BtcDepositAddressIdentifier,proto3" json:"BtcDepositAddressIdentifier,omitempty"`
}

func (m *RefundTxAccountSnap) Reset()         { *m = RefundTxAccountSnap{} }
func (m *RefundTxAccountSnap) String() string { return proto.CompactTextString(m) }
func (*RefundTxAccountSnap) ProtoMessage()    {}
func (*RefundTxAccountSnap) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b8c38580db6c779, []int{2}
}
func (m *RefundTxAccountSnap) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RefundTxAccountSnap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RefundTxAccountSnap.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RefundTxAccountSnap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundTxAccountSnap.Merge(m, src)
}
func (m *RefundTxAccountSnap) XXX_Size() int {
	return m.Size()
}
func (m *RefundTxAccountSnap) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundTxAccountSnap.DiscardUnknown(m)
}

var xxx_messageInfo_RefundTxAccountSnap proto.InternalMessageInfo

func (m *RefundTxAccountSnap) GetAmount() uint64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *RefundTxAccountSnap) GetBtcDepositAddress() string {
	if m != nil {
		return m.BtcDepositAddress
	}
	return ""
}

func (m *RefundTxAccountSnap) GetBtcDepositAddressIdentifier() uint32 {
	if m != nil {
		return m.BtcDepositAddressIdentifier
	}
	return 0
}

type RefundTxSnapshot struct {
	ReserveId                uint64                 `protobuf:"varint,1,opt,name=ReserveId,proto3" json:"ReserveId,omitempty"`
	RoundId                  uint64                 `protobuf:"varint,2,opt,name=RoundId,proto3" json:"RoundId,omitempty"`
	RefundAccounts           []*RefundTxAccountSnap `protobuf:"bytes,3,rep,name=refundAccounts,proto3" json:"refundAccounts,omitempty"`
	EndBlockerHeightTwilight int64                  `protobuf:"varint,4,opt,name=EndBlockerHeightTwilight,proto3" json:"EndBlockerHeightTwilight,omitempty"`
}

func (m *RefundTxSnapshot) Reset()         { *m = RefundTxSnapshot{} }
func (m *RefundTxSnapshot) String() string { return proto.CompactTextString(m) }
func (*RefundTxSnapshot) ProtoMessage()    {}
func (*RefundTxSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b8c38580db6c779, []int{3}
}
func (m *RefundTxSnapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *RefundTxSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_RefundTxSnapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *RefundTxSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RefundTxSnapshot.Merge(m, src)
}
func (m *RefundTxSnapshot) XXX_Size() int {
	return m.Size()
}
func (m *RefundTxSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_RefundTxSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_RefundTxSnapshot proto.InternalMessageInfo

func (m *RefundTxSnapshot) GetReserveId() uint64 {
	if m != nil {
		return m.ReserveId
	}
	return 0
}

func (m *RefundTxSnapshot) GetRoundId() uint64 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

func (m *RefundTxSnapshot) GetRefundAccounts() []*RefundTxAccountSnap {
	if m != nil {
		return m.RefundAccounts
	}
	return nil
}

func (m *RefundTxSnapshot) GetEndBlockerHeightTwilight() int64 {
	if m != nil {
		return m.EndBlockerHeightTwilight
	}
	return 0
}

func init() {
	proto.RegisterType((*IndividualTwilightReserveAccountBalance)(nil), "twilightproject.nyks.volt.IndividualTwilightReserveAccountBalance")
	proto.RegisterType((*ClearingAccount)(nil), "twilightproject.nyks.volt.ClearingAccount")
	proto.RegisterType((*RefundTxAccountSnap)(nil), "twilightproject.nyks.volt.RefundTxAccountSnap")
	proto.RegisterType((*RefundTxSnapshot)(nil), "twilightproject.nyks.volt.RefundTxSnapshot")
}

func init() {
	proto.RegisterFile("twilightproject/nyks/volt/clearing.proto", fileDescriptor_9b8c38580db6c779)
}

var fileDescriptor_9b8c38580db6c779 = []byte{
	// 427 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x53, 0x4d, 0x8f, 0xd3, 0x30,
	0x10, 0xad, 0x37, 0x4b, 0xd1, 0x0e, 0x82, 0x05, 0x23, 0xad, 0x82, 0x58, 0x45, 0x55, 0x2e, 0xe4,
	0x00, 0xa9, 0x04, 0x37, 0xc4, 0x81, 0x06, 0x90, 0xc8, 0xd5, 0xac, 0x40, 0xe2, 0x82, 0x82, 0xed,
	0xdd, 0x9a, 0x06, 0x3b, 0xb2, 0x9d, 0x7e, 0xf0, 0x2b, 0xb8, 0x23, 0xfe, 0x0f, 0xc7, 0x1e, 0x39,
	0x21, 0xd4, 0xfe, 0x11, 0x14, 0xe3, 0x40, 0xe9, 0x17, 0x9c, 0x38, 0x7a, 0xde, 0xd3, 0x7b, 0xe3,
	0x79, 0x33, 0x90, 0xd8, 0x89, 0x28, 0xc5, 0xc5, 0xd0, 0x56, 0x5a, 0xbd, 0xe3, 0xd4, 0xf6, 0xe5,
	0x6c, 0x64, 0xfa, 0x63, 0x55, 0xda, 0x3e, 0x2d, 0x79, 0xa1, 0x85, 0xbc, 0x48, 0x2b, 0xad, 0xac,
	0xc2, 0xb7, 0xd6, 0x98, 0x69, 0xc3, 0x4c, 0x1b, 0x66, 0xfc, 0x06, 0xee, 0xe4, 0x92, 0x89, 0xb1,
	0x60, 0x75, 0x51, 0x9e, 0x79, 0x1a, 0xe1, 0x86, 0xeb, 0x31, 0x1f, 0x50, 0xaa, 0x6a, 0x69, 0xb3,
	0xa2, 0x2c, 0x24, 0xe5, 0xf8, 0x14, 0x8e, 0x3c, 0x90, 0xb3, 0x10, 0xf5, 0x50, 0x72, 0x48, 0x7e,
	0x17, 0xf0, 0x09, 0x74, 0x07, 0xef, 0x1b, 0x7a, 0x78, 0xe0, 0x20, 0xff, 0x8a, 0x3f, 0x05, 0x70,
	0xfc, 0xc4, 0xb7, 0xe3, 0x05, 0x71, 0x02, 0xc7, 0xad, 0xd5, 0x80, 0x31, 0xcd, 0x8d, 0x71, 0x7a,
	0x47, 0x64, 0xbd, 0x8c, 0xef, 0xc2, 0x8d, 0xcc, 0xd2, 0xa7, 0xbc, 0x52, 0x46, 0xfc, 0xe2, 0x1e,
	0x38, 0xee, 0x26, 0x80, 0x1f, 0xc3, 0xed, 0x8d, 0x62, 0xce, 0xb8, 0xb4, 0xe2, 0x5c, 0x70, 0x1d,
	0x06, 0x3d, 0x94, 0x5c, 0x25, 0xfb, 0x28, 0x38, 0x05, 0x9c, 0x59, 0xfa, 0x4a, 0xd8, 0x21, 0xd3,
	0xc5, 0xa4, 0x35, 0x3c, 0x74, 0x86, 0x5b, 0x10, 0x9c, 0xc1, 0xe9, 0x66, 0x75, 0xc5, 0xf2, 0x92,
	0xb3, 0xdc, 0xcb, 0xc1, 0x1f, 0xe0, 0x64, 0xeb, 0xc0, 0x4d, 0xd8, 0xed, 0x05, 0xc9, 0x95, 0xfb,
	0x59, 0xba, 0x33, 0xbe, 0xf4, 0x1f, 0xb3, 0x23, 0x3b, 0x1c, 0xe2, 0xcf, 0x08, 0x6e, 0x12, 0x7e,
	0x5e, 0x4b, 0x76, 0x36, 0xf5, 0xd8, 0x0b, 0x59, 0x54, 0x2b, 0x69, 0xa2, 0xd5, 0x34, 0xff, 0x77,
	0x1e, 0xf1, 0x37, 0x04, 0xd7, 0xdb, 0xfe, 0x9a, 0xc6, 0xcc, 0x50, 0xd9, 0xbf, 0x2c, 0x62, 0x08,
	0x97, 0x89, 0xaa, 0x25, 0xcb, 0x99, 0xdf, 0xc4, 0xf6, 0x89, 0x5f, 0xc2, 0x35, 0xed, 0xb4, 0xfc,
	0x4f, 0x4d, 0x18, 0xb8, 0x01, 0xa7, 0x7b, 0x06, 0xbc, 0x65, 0x38, 0x64, 0x4d, 0x05, 0x3f, 0x84,
	0xf0, 0x99, 0x64, 0x59, 0xa9, 0xe8, 0x88, 0xeb, 0xe7, 0xbc, 0x11, 0x6a, 0xd3, 0x70, 0xab, 0x13,
	0x90, 0x9d, 0x78, 0xf6, 0xe8, 0xcb, 0x22, 0x42, 0xf3, 0x45, 0x84, 0xbe, 0x2f, 0x22, 0xf4, 0x71,
	0x19, 0x75, 0xe6, 0xcb, 0xa8, 0xf3, 0x75, 0x19, 0x75, 0x5e, 0xc7, 0x6d, 0x53, 0xf7, 0xfe, 0xb8,
	0xef, 0xe9, 0xcf, 0x0b, 0xb7, 0xb3, 0x8a, 0x9b, 0xb7, 0x5d, 0x77, 0xdf, 0x0f, 0x7e, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x3c, 0x45, 0x23, 0x4d, 0x0b, 0x04, 0x00, 0x00,
}

func (m *IndividualTwilightReserveAccountBalance) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *IndividualTwilightReserveAccountBalance) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *IndividualTwilightReserveAccountBalance) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.Amount != 0 {
		i = encodeVarintClearing(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x10
	}
	if m.ReserveId != 0 {
		i = encodeVarintClearing(dAtA, i, uint64(m.ReserveId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *ClearingAccount) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *ClearingAccount) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *ClearingAccount) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReserveAccountBalances) > 0 {
		for iNdEx := len(m.ReserveAccountBalances) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.ReserveAccountBalances[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintClearing(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x32
		}
	}
	if m.BtcWithdrawAddressIdentifier != 0 {
		i = encodeVarintClearing(dAtA, i, uint64(m.BtcWithdrawAddressIdentifier))
		i--
		dAtA[i] = 0x28
	}
	if len(m.BtcWithdrawAddress) > 0 {
		i -= len(m.BtcWithdrawAddress)
		copy(dAtA[i:], m.BtcWithdrawAddress)
		i = encodeVarintClearing(dAtA, i, uint64(len(m.BtcWithdrawAddress)))
		i--
		dAtA[i] = 0x22
	}
	if m.BtcDepositAddressIdentifier != 0 {
		i = encodeVarintClearing(dAtA, i, uint64(m.BtcDepositAddressIdentifier))
		i--
		dAtA[i] = 0x18
	}
	if len(m.BtcDepositAddress) > 0 {
		i -= len(m.BtcDepositAddress)
		copy(dAtA[i:], m.BtcDepositAddress)
		i = encodeVarintClearing(dAtA, i, uint64(len(m.BtcDepositAddress)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TwilightAddress) > 0 {
		i -= len(m.TwilightAddress)
		copy(dAtA[i:], m.TwilightAddress)
		i = encodeVarintClearing(dAtA, i, uint64(len(m.TwilightAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *RefundTxAccountSnap) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RefundTxAccountSnap) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RefundTxAccountSnap) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.BtcDepositAddressIdentifier != 0 {
		i = encodeVarintClearing(dAtA, i, uint64(m.BtcDepositAddressIdentifier))
		i--
		dAtA[i] = 0x18
	}
	if len(m.BtcDepositAddress) > 0 {
		i -= len(m.BtcDepositAddress)
		copy(dAtA[i:], m.BtcDepositAddress)
		i = encodeVarintClearing(dAtA, i, uint64(len(m.BtcDepositAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.Amount != 0 {
		i = encodeVarintClearing(dAtA, i, uint64(m.Amount))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *RefundTxSnapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *RefundTxSnapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *RefundTxSnapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.EndBlockerHeightTwilight != 0 {
		i = encodeVarintClearing(dAtA, i, uint64(m.EndBlockerHeightTwilight))
		i--
		dAtA[i] = 0x20
	}
	if len(m.RefundAccounts) > 0 {
		for iNdEx := len(m.RefundAccounts) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.RefundAccounts[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintClearing(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x1a
		}
	}
	if m.RoundId != 0 {
		i = encodeVarintClearing(dAtA, i, uint64(m.RoundId))
		i--
		dAtA[i] = 0x10
	}
	if m.ReserveId != 0 {
		i = encodeVarintClearing(dAtA, i, uint64(m.ReserveId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintClearing(dAtA []byte, offset int, v uint64) int {
	offset -= sovClearing(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *IndividualTwilightReserveAccountBalance) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReserveId != 0 {
		n += 1 + sovClearing(uint64(m.ReserveId))
	}
	if m.Amount != 0 {
		n += 1 + sovClearing(uint64(m.Amount))
	}
	return n
}

func (m *ClearingAccount) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TwilightAddress)
	if l > 0 {
		n += 1 + l + sovClearing(uint64(l))
	}
	l = len(m.BtcDepositAddress)
	if l > 0 {
		n += 1 + l + sovClearing(uint64(l))
	}
	if m.BtcDepositAddressIdentifier != 0 {
		n += 1 + sovClearing(uint64(m.BtcDepositAddressIdentifier))
	}
	l = len(m.BtcWithdrawAddress)
	if l > 0 {
		n += 1 + l + sovClearing(uint64(l))
	}
	if m.BtcWithdrawAddressIdentifier != 0 {
		n += 1 + sovClearing(uint64(m.BtcWithdrawAddressIdentifier))
	}
	if len(m.ReserveAccountBalances) > 0 {
		for _, e := range m.ReserveAccountBalances {
			l = e.Size()
			n += 1 + l + sovClearing(uint64(l))
		}
	}
	return n
}

func (m *RefundTxAccountSnap) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.Amount != 0 {
		n += 1 + sovClearing(uint64(m.Amount))
	}
	l = len(m.BtcDepositAddress)
	if l > 0 {
		n += 1 + l + sovClearing(uint64(l))
	}
	if m.BtcDepositAddressIdentifier != 0 {
		n += 1 + sovClearing(uint64(m.BtcDepositAddressIdentifier))
	}
	return n
}

func (m *RefundTxSnapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ReserveId != 0 {
		n += 1 + sovClearing(uint64(m.ReserveId))
	}
	if m.RoundId != 0 {
		n += 1 + sovClearing(uint64(m.RoundId))
	}
	if len(m.RefundAccounts) > 0 {
		for _, e := range m.RefundAccounts {
			l = e.Size()
			n += 1 + l + sovClearing(uint64(l))
		}
	}
	if m.EndBlockerHeightTwilight != 0 {
		n += 1 + sovClearing(uint64(m.EndBlockerHeightTwilight))
	}
	return n
}

func sovClearing(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozClearing(x uint64) (n int) {
	return sovClearing(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *IndividualTwilightReserveAccountBalance) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClearing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: IndividualTwilightReserveAccountBalance: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: IndividualTwilightReserveAccountBalance: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveId", wireType)
			}
			m.ReserveId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReserveId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClearing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClearing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *ClearingAccount) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClearing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: ClearingAccount: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: ClearingAccount: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwilightAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClearing
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClearing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TwilightAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcDepositAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClearing
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClearing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcDepositAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcDepositAddressIdentifier", wireType)
			}
			m.BtcDepositAddressIdentifier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BtcDepositAddressIdentifier |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcWithdrawAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClearing
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClearing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcWithdrawAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcWithdrawAddressIdentifier", wireType)
			}
			m.BtcWithdrawAddressIdentifier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BtcWithdrawAddressIdentifier |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveAccountBalances", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClearing
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClearing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ReserveAccountBalances = append(m.ReserveAccountBalances, &IndividualTwilightReserveAccountBalance{})
			if err := m.ReserveAccountBalances[len(m.ReserveAccountBalances)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipClearing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClearing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RefundTxAccountSnap) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClearing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RefundTxAccountSnap: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RefundTxAccountSnap: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Amount", wireType)
			}
			m.Amount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Amount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcDepositAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthClearing
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthClearing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcDepositAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcDepositAddressIdentifier", wireType)
			}
			m.BtcDepositAddressIdentifier = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BtcDepositAddressIdentifier |= uint32(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClearing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClearing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *RefundTxSnapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowClearing
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: RefundTxSnapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: RefundTxSnapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveId", wireType)
			}
			m.ReserveId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReserveId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoundId", wireType)
			}
			m.RoundId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoundId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field RefundAccounts", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthClearing
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthClearing
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.RefundAccounts = append(m.RefundAccounts, &RefundTxAccountSnap{})
			if err := m.RefundAccounts[len(m.RefundAccounts)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field EndBlockerHeightTwilight", wireType)
			}
			m.EndBlockerHeightTwilight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.EndBlockerHeightTwilight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipClearing(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthClearing
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipClearing(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowClearing
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowClearing
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthClearing
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupClearing
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthClearing
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthClearing        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowClearing          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupClearing = fmt.Errorf("proto: unexpected end of group")
)
