// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twilightproject/nyks/volt/deposit.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type BtcDepositAddress struct {
	BtcDepositAddress           string `protobuf:"bytes,1,opt,name=btcDepositAddress,proto3" json:"btcDepositAddress,omitempty"`
	BtcSatoshiTestAmount        uint64 `protobuf:"varint,2,opt,name=btcSatoshiTestAmount,proto3" json:"btcSatoshiTestAmount,omitempty"`
	TwilightStakingAmount       uint64 `protobuf:"varint,3,opt,name=twilightStakingAmount,proto3" json:"twilightStakingAmount,omitempty"`
	TwilightAddress             string `protobuf:"bytes,4,opt,name=twilightAddress,proto3" json:"twilightAddress,omitempty"`
	IsConfirmed                 bool   `protobuf:"varint,5,opt,name=isConfirmed,proto3" json:"isConfirmed,omitempty"`
	CreationTwilightBlockHeight int64  `protobuf:"varint,6,opt,name=CreationTwilightBlockHeight,proto3" json:"CreationTwilightBlockHeight,omitempty"`
}

func (m *BtcDepositAddress) Reset()         { *m = BtcDepositAddress{} }
func (m *BtcDepositAddress) String() string { return proto.CompactTextString(m) }
func (*BtcDepositAddress) ProtoMessage()    {}
func (*BtcDepositAddress) Descriptor() ([]byte, []int) {
	return fileDescriptor_4a764dfa5d4418f7, []int{0}
}
func (m *BtcDepositAddress) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *BtcDepositAddress) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_BtcDepositAddress.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *BtcDepositAddress) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BtcDepositAddress.Merge(m, src)
}
func (m *BtcDepositAddress) XXX_Size() int {
	return m.Size()
}
func (m *BtcDepositAddress) XXX_DiscardUnknown() {
	xxx_messageInfo_BtcDepositAddress.DiscardUnknown(m)
}

var xxx_messageInfo_BtcDepositAddress proto.InternalMessageInfo

func (m *BtcDepositAddress) GetBtcDepositAddress() string {
	if m != nil {
		return m.BtcDepositAddress
	}
	return ""
}

func (m *BtcDepositAddress) GetBtcSatoshiTestAmount() uint64 {
	if m != nil {
		return m.BtcSatoshiTestAmount
	}
	return 0
}

func (m *BtcDepositAddress) GetTwilightStakingAmount() uint64 {
	if m != nil {
		return m.TwilightStakingAmount
	}
	return 0
}

func (m *BtcDepositAddress) GetTwilightAddress() string {
	if m != nil {
		return m.TwilightAddress
	}
	return ""
}

func (m *BtcDepositAddress) GetIsConfirmed() bool {
	if m != nil {
		return m.IsConfirmed
	}
	return false
}

func (m *BtcDepositAddress) GetCreationTwilightBlockHeight() int64 {
	if m != nil {
		return m.CreationTwilightBlockHeight
	}
	return 0
}

func init() {
	proto.RegisterType((*BtcDepositAddress)(nil), "twilightproject.nyks.volt.BtcDepositAddress")
}

func init() {
	proto.RegisterFile("twilightproject/nyks/volt/deposit.proto", fileDescriptor_4a764dfa5d4418f7)
}

var fileDescriptor_4a764dfa5d4418f7 = []byte{
	// 282 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x52, 0x2f, 0x29, 0xcf, 0xcc,
	0xc9, 0x4c, 0xcf, 0x28, 0x29, 0x28, 0xca, 0xcf, 0x4a, 0x4d, 0x2e, 0xd1, 0xcf, 0xab, 0xcc, 0x2e,
	0xd6, 0x2f, 0xcb, 0xcf, 0x29, 0xd1, 0x4f, 0x49, 0x2d, 0xc8, 0x2f, 0xce, 0x2c, 0xd1, 0x2b, 0x28,
	0xca, 0x2f, 0xc9, 0x17, 0x92, 0x44, 0x53, 0xa8, 0x07, 0x52, 0xa8, 0x07, 0x52, 0xa8, 0xb4, 0x93,
	0x89, 0x4b, 0xd0, 0xa9, 0x24, 0xd9, 0x05, 0xa2, 0xde, 0x31, 0x25, 0xa5, 0x28, 0xb5, 0xb8, 0x58,
	0x48, 0x87, 0x4b, 0x30, 0x09, 0x5d, 0x50, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0x53, 0x42,
	0xc8, 0x88, 0x4b, 0x24, 0xa9, 0x24, 0x39, 0x38, 0xb1, 0x24, 0xbf, 0x38, 0x23, 0x33, 0x24, 0xb5,
	0xb8, 0xc4, 0x31, 0x37, 0xbf, 0x34, 0xaf, 0x44, 0x82, 0x49, 0x81, 0x51, 0x83, 0x25, 0x08, 0xab,
	0x9c, 0x90, 0x09, 0x97, 0x28, 0xcc, 0x51, 0xc1, 0x25, 0x89, 0xd9, 0x99, 0x79, 0xe9, 0x50, 0x4d,
	0xcc, 0x60, 0x4d, 0xd8, 0x25, 0x85, 0x34, 0xb8, 0xf8, 0x61, 0x12, 0x30, 0x57, 0xb1, 0x80, 0x5d,
	0x85, 0x2e, 0x2c, 0xa4, 0xc0, 0xc5, 0x9d, 0x59, 0xec, 0x9c, 0x9f, 0x97, 0x96, 0x59, 0x94, 0x9b,
	0x9a, 0x22, 0xc1, 0xaa, 0xc0, 0xa8, 0xc1, 0x11, 0x84, 0x2c, 0x24, 0xe4, 0xc0, 0x25, 0xed, 0x5c,
	0x94, 0x9a, 0x58, 0x92, 0x99, 0x9f, 0x17, 0x02, 0xd5, 0xec, 0x94, 0x93, 0x9f, 0x9c, 0xed, 0x91,
	0x0a, 0x62, 0x4a, 0xb0, 0x29, 0x30, 0x6a, 0x30, 0x07, 0xe1, 0x53, 0xe2, 0x64, 0x73, 0xe2, 0x91,
	0x1c, 0xe3, 0x85, 0x47, 0x72, 0x8c, 0x0f, 0x1e, 0xc9, 0x31, 0x4e, 0x78, 0x2c, 0xc7, 0x70, 0xe1,
	0xb1, 0x1c, 0xc3, 0x8d, 0xc7, 0x72, 0x0c, 0x51, 0x4a, 0x30, 0xe7, 0xe8, 0xa2, 0x44, 0x4d, 0x05,
	0x24, 0x72, 0x4a, 0x2a, 0x0b, 0x52, 0x8b, 0x93, 0xd8, 0xc0, 0x71, 0x63, 0x0c, 0x08, 0x00, 0x00,
	0xff, 0xff, 0x6f, 0x32, 0xac, 0x05, 0xc6, 0x01, 0x00, 0x00,
}

func (m *BtcDepositAddress) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *BtcDepositAddress) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *BtcDepositAddress) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.CreationTwilightBlockHeight != 0 {
		i = encodeVarintDeposit(dAtA, i, uint64(m.CreationTwilightBlockHeight))
		i--
		dAtA[i] = 0x30
	}
	if m.IsConfirmed {
		i--
		if m.IsConfirmed {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x28
	}
	if len(m.TwilightAddress) > 0 {
		i -= len(m.TwilightAddress)
		copy(dAtA[i:], m.TwilightAddress)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.TwilightAddress)))
		i--
		dAtA[i] = 0x22
	}
	if m.TwilightStakingAmount != 0 {
		i = encodeVarintDeposit(dAtA, i, uint64(m.TwilightStakingAmount))
		i--
		dAtA[i] = 0x18
	}
	if m.BtcSatoshiTestAmount != 0 {
		i = encodeVarintDeposit(dAtA, i, uint64(m.BtcSatoshiTestAmount))
		i--
		dAtA[i] = 0x10
	}
	if len(m.BtcDepositAddress) > 0 {
		i -= len(m.BtcDepositAddress)
		copy(dAtA[i:], m.BtcDepositAddress)
		i = encodeVarintDeposit(dAtA, i, uint64(len(m.BtcDepositAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintDeposit(dAtA []byte, offset int, v uint64) int {
	offset -= sovDeposit(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *BtcDepositAddress) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.BtcDepositAddress)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	if m.BtcSatoshiTestAmount != 0 {
		n += 1 + sovDeposit(uint64(m.BtcSatoshiTestAmount))
	}
	if m.TwilightStakingAmount != 0 {
		n += 1 + sovDeposit(uint64(m.TwilightStakingAmount))
	}
	l = len(m.TwilightAddress)
	if l > 0 {
		n += 1 + l + sovDeposit(uint64(l))
	}
	if m.IsConfirmed {
		n += 2
	}
	if m.CreationTwilightBlockHeight != 0 {
		n += 1 + sovDeposit(uint64(m.CreationTwilightBlockHeight))
	}
	return n
}

func sovDeposit(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozDeposit(x uint64) (n int) {
	return sovDeposit(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *BtcDepositAddress) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowDeposit
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: BtcDepositAddress: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: BtcDepositAddress: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcDepositAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcDepositAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcSatoshiTestAmount", wireType)
			}
			m.BtcSatoshiTestAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BtcSatoshiTestAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwilightStakingAmount", wireType)
			}
			m.TwilightStakingAmount = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TwilightStakingAmount |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwilightAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthDeposit
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthDeposit
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TwilightAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field IsConfirmed", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.IsConfirmed = bool(v != 0)
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field CreationTwilightBlockHeight", wireType)
			}
			m.CreationTwilightBlockHeight = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.CreationTwilightBlockHeight |= int64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipDeposit(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthDeposit
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipDeposit(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowDeposit
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowDeposit
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthDeposit
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupDeposit
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthDeposit
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthDeposit        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowDeposit          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupDeposit = fmt.Errorf("proto: unexpected end of group")
)
