// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twilightproject/nyks/volt/events.proto

package types

import (
	fmt "fmt"
	proto "github.com/cosmos/gogoproto/proto"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type EventReserveWithdrawSnapshot struct {
	Message   string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ReserveId uint64 `protobuf:"varint,2,opt,name=reserveId,proto3" json:"reserveId,omitempty"`
	RoundId   uint64 `protobuf:"varint,3,opt,name=roundId,proto3" json:"roundId,omitempty"`
}

func (m *EventReserveWithdrawSnapshot) Reset()         { *m = EventReserveWithdrawSnapshot{} }
func (m *EventReserveWithdrawSnapshot) String() string { return proto.CompactTextString(m) }
func (*EventReserveWithdrawSnapshot) ProtoMessage()    {}
func (*EventReserveWithdrawSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b774ab242cd51d6, []int{0}
}
func (m *EventReserveWithdrawSnapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventReserveWithdrawSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventReserveWithdrawSnapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventReserveWithdrawSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventReserveWithdrawSnapshot.Merge(m, src)
}
func (m *EventReserveWithdrawSnapshot) XXX_Size() int {
	return m.Size()
}
func (m *EventReserveWithdrawSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_EventReserveWithdrawSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_EventReserveWithdrawSnapshot proto.InternalMessageInfo

func (m *EventReserveWithdrawSnapshot) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *EventReserveWithdrawSnapshot) GetReserveId() uint64 {
	if m != nil {
		return m.ReserveId
	}
	return 0
}

func (m *EventReserveWithdrawSnapshot) GetRoundId() uint64 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

type EventRefundTxSnapshot struct {
	Message   string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ReserveId uint64 `protobuf:"varint,2,opt,name=reserveId,proto3" json:"reserveId,omitempty"`
	RoundId   uint64 `protobuf:"varint,3,opt,name=roundId,proto3" json:"roundId,omitempty"`
}

func (m *EventRefundTxSnapshot) Reset()         { *m = EventRefundTxSnapshot{} }
func (m *EventRefundTxSnapshot) String() string { return proto.CompactTextString(m) }
func (*EventRefundTxSnapshot) ProtoMessage()    {}
func (*EventRefundTxSnapshot) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b774ab242cd51d6, []int{1}
}
func (m *EventRefundTxSnapshot) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventRefundTxSnapshot) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventRefundTxSnapshot.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventRefundTxSnapshot) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventRefundTxSnapshot.Merge(m, src)
}
func (m *EventRefundTxSnapshot) XXX_Size() int {
	return m.Size()
}
func (m *EventRefundTxSnapshot) XXX_DiscardUnknown() {
	xxx_messageInfo_EventRefundTxSnapshot.DiscardUnknown(m)
}

var xxx_messageInfo_EventRefundTxSnapshot proto.InternalMessageInfo

func (m *EventRefundTxSnapshot) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *EventRefundTxSnapshot) GetReserveId() uint64 {
	if m != nil {
		return m.ReserveId
	}
	return 0
}

func (m *EventRefundTxSnapshot) GetRoundId() uint64 {
	if m != nil {
		return m.RoundId
	}
	return 0
}

type EventSignerApplication struct {
	Message       string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	ApplicationId uint64 `protobuf:"varint,2,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
}

func (m *EventSignerApplication) Reset()         { *m = EventSignerApplication{} }
func (m *EventSignerApplication) String() string { return proto.CompactTextString(m) }
func (*EventSignerApplication) ProtoMessage()    {}
func (*EventSignerApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b774ab242cd51d6, []int{2}
}
func (m *EventSignerApplication) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventSignerApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventSignerApplication.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventSignerApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventSignerApplication.Merge(m, src)
}
func (m *EventSignerApplication) XXX_Size() int {
	return m.Size()
}
func (m *EventSignerApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_EventSignerApplication.DiscardUnknown(m)
}

var xxx_messageInfo_EventSignerApplication proto.InternalMessageInfo

func (m *EventSignerApplication) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *EventSignerApplication) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

type EventAcceptSigners struct {
	Message      string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	FragmentId   uint64 `protobuf:"varint,2,opt,name=fragmentId,proto3" json:"fragmentId,omitempty"`
	JudgeAddress string `protobuf:"bytes,4,opt,name=judgeAddress,proto3" json:"judgeAddress,omitempty"`
}

func (m *EventAcceptSigners) Reset()         { *m = EventAcceptSigners{} }
func (m *EventAcceptSigners) String() string { return proto.CompactTextString(m) }
func (*EventAcceptSigners) ProtoMessage()    {}
func (*EventAcceptSigners) Descriptor() ([]byte, []int) {
	return fileDescriptor_9b774ab242cd51d6, []int{3}
}
func (m *EventAcceptSigners) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *EventAcceptSigners) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_EventAcceptSigners.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *EventAcceptSigners) XXX_Merge(src proto.Message) {
	xxx_messageInfo_EventAcceptSigners.Merge(m, src)
}
func (m *EventAcceptSigners) XXX_Size() int {
	return m.Size()
}
func (m *EventAcceptSigners) XXX_DiscardUnknown() {
	xxx_messageInfo_EventAcceptSigners.DiscardUnknown(m)
}

var xxx_messageInfo_EventAcceptSigners proto.InternalMessageInfo

func (m *EventAcceptSigners) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *EventAcceptSigners) GetFragmentId() uint64 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *EventAcceptSigners) GetJudgeAddress() string {
	if m != nil {
		return m.JudgeAddress
	}
	return ""
}

func init() {
	proto.RegisterType((*EventReserveWithdrawSnapshot)(nil), "twilightproject.nyks.volt.EventReserveWithdrawSnapshot")
	proto.RegisterType((*EventRefundTxSnapshot)(nil), "twilightproject.nyks.volt.EventRefundTxSnapshot")
	proto.RegisterType((*EventSignerApplication)(nil), "twilightproject.nyks.volt.EventSignerApplication")
	proto.RegisterType((*EventAcceptSigners)(nil), "twilightproject.nyks.volt.EventAcceptSigners")
}

func init() {
	proto.RegisterFile("twilightproject/nyks/volt/events.proto", fileDescriptor_9b774ab242cd51d6)
}

var fileDescriptor_9b774ab242cd51d6 = []byte{
	// 302 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x92, 0xb1, 0x4e, 0xc3, 0x30,
	0x18, 0x84, 0x6b, 0xa8, 0x40, 0xb5, 0x60, 0x89, 0x04, 0x0a, 0x52, 0x65, 0x55, 0x11, 0x42, 0x5d,
	0x68, 0x06, 0x56, 0x96, 0x20, 0x31, 0x74, 0x4d, 0x91, 0x40, 0x6c, 0x26, 0xfe, 0x9b, 0xb8, 0xa4,
	0xb6, 0x65, 0x3b, 0x69, 0xfb, 0x16, 0x3c, 0x16, 0x63, 0x47, 0x46, 0x94, 0xbc, 0x08, 0x4a, 0xda,
	0xb4, 0x84, 0xa1, 0x1b, 0xe3, 0x7f, 0xbe, 0xbb, 0x6f, 0xf0, 0xe1, 0x1b, 0xbb, 0xe0, 0x29, 0x8f,
	0x13, 0xab, 0xb4, 0x9c, 0x41, 0x64, 0x7d, 0xb1, 0x7a, 0x37, 0x7e, 0x2e, 0x53, 0xeb, 0x43, 0x0e,
	0xc2, 0x9a, 0x91, 0xd2, 0xd2, 0x4a, 0xe7, 0xea, 0x8f, 0x6f, 0x54, 0xf9, 0x46, 0x95, 0xcf, 0x53,
	0xb8, 0xff, 0x58, 0x59, 0x43, 0x30, 0xa0, 0x73, 0x78, 0xe6, 0x36, 0x61, 0x9a, 0x2e, 0x26, 0x82,
	0x2a, 0x93, 0x48, 0xeb, 0xb8, 0xf8, 0x74, 0x0e, 0xc6, 0xd0, 0x18, 0x5c, 0x34, 0x40, 0xc3, 0x5e,
	0xd8, 0x9c, 0x4e, 0x1f, 0xf7, 0xf4, 0x26, 0x34, 0x66, 0xee, 0xd1, 0x00, 0x0d, 0xbb, 0xe1, 0x5e,
	0xa8, 0x72, 0x5a, 0x66, 0x82, 0x8d, 0x99, 0x7b, 0x5c, 0xbf, 0x35, 0xa7, 0xc7, 0xf1, 0xc5, 0x96,
	0x38, 0xcd, 0x04, 0x7b, 0x5a, 0xfe, 0x23, 0xea, 0x05, 0x5f, 0xd6, 0xa8, 0x09, 0x8f, 0x05, 0xe8,
	0x40, 0xa9, 0x94, 0x47, 0xd4, 0x72, 0x29, 0x0e, 0xb0, 0xae, 0xf1, 0x39, 0xdd, 0x1b, 0x77, 0xbc,
	0xb6, 0xe8, 0x69, 0xec, 0xd4, 0xcd, 0x41, 0x14, 0x81, 0xda, 0xf6, 0x9b, 0x03, 0xad, 0x04, 0xe3,
	0xa9, 0xa6, 0xf1, 0x1c, 0x84, 0xdd, 0x55, 0xfe, 0x52, 0x1c, 0x0f, 0x9f, 0xcd, 0x32, 0x16, 0x43,
	0xc0, 0x98, 0x06, 0x63, 0xdc, 0x6e, 0x1d, 0x6f, 0x69, 0x0f, 0xf7, 0x9f, 0x05, 0x41, 0xeb, 0x82,
	0xa0, 0xef, 0x82, 0xa0, 0x8f, 0x92, 0x74, 0xd6, 0x25, 0xe9, 0x7c, 0x95, 0xa4, 0xf3, 0xea, 0x35,
	0xff, 0x7b, 0xdb, 0x1a, 0xc2, 0x72, 0x33, 0x05, 0xbb, 0x52, 0x60, 0xde, 0x4e, 0xea, 0x29, 0xdc,
	0xfd, 0x04, 0x00, 0x00, 0xff, 0xff, 0xad, 0x96, 0x45, 0x19, 0x34, 0x02, 0x00, 0x00,
}

func (m *EventReserveWithdrawSnapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventReserveWithdrawSnapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventReserveWithdrawSnapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RoundId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.RoundId))
		i--
		dAtA[i] = 0x18
	}
	if m.ReserveId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.ReserveId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventRefundTxSnapshot) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventRefundTxSnapshot) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventRefundTxSnapshot) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.RoundId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.RoundId))
		i--
		dAtA[i] = 0x18
	}
	if m.ReserveId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.ReserveId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventSignerApplication) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventSignerApplication) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventSignerApplication) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ApplicationId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.ApplicationId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *EventAcceptSigners) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *EventAcceptSigners) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *EventAcceptSigners) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.JudgeAddress) > 0 {
		i -= len(m.JudgeAddress)
		copy(dAtA[i:], m.JudgeAddress)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.JudgeAddress)))
		i--
		dAtA[i] = 0x22
	}
	if m.FragmentId != 0 {
		i = encodeVarintEvents(dAtA, i, uint64(m.FragmentId))
		i--
		dAtA[i] = 0x10
	}
	if len(m.Message) > 0 {
		i -= len(m.Message)
		copy(dAtA[i:], m.Message)
		i = encodeVarintEvents(dAtA, i, uint64(len(m.Message)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func encodeVarintEvents(dAtA []byte, offset int, v uint64) int {
	offset -= sovEvents(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *EventReserveWithdrawSnapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.ReserveId != 0 {
		n += 1 + sovEvents(uint64(m.ReserveId))
	}
	if m.RoundId != 0 {
		n += 1 + sovEvents(uint64(m.RoundId))
	}
	return n
}

func (m *EventRefundTxSnapshot) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.ReserveId != 0 {
		n += 1 + sovEvents(uint64(m.ReserveId))
	}
	if m.RoundId != 0 {
		n += 1 + sovEvents(uint64(m.RoundId))
	}
	return n
}

func (m *EventSignerApplication) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.ApplicationId != 0 {
		n += 1 + sovEvents(uint64(m.ApplicationId))
	}
	return n
}

func (m *EventAcceptSigners) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Message)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	if m.FragmentId != 0 {
		n += 1 + sovEvents(uint64(m.FragmentId))
	}
	l = len(m.JudgeAddress)
	if l > 0 {
		n += 1 + l + sovEvents(uint64(l))
	}
	return n
}

func sovEvents(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozEvents(x uint64) (n int) {
	return sovEvents(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *EventReserveWithdrawSnapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventReserveWithdrawSnapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventReserveWithdrawSnapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveId", wireType)
			}
			m.ReserveId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReserveId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoundId", wireType)
			}
			m.RoundId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoundId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventRefundTxSnapshot) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventRefundTxSnapshot: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventRefundTxSnapshot: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveId", wireType)
			}
			m.ReserveId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ReserveId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field RoundId", wireType)
			}
			m.RoundId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.RoundId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventSignerApplication) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventSignerApplication: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventSignerApplication: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationId", wireType)
			}
			m.ApplicationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApplicationId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *EventAcceptSigners) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: EventAcceptSigners: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: EventAcceptSigners: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Message", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Message = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FragmentId", wireType)
			}
			m.FragmentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FragmentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JudgeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthEvents
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthEvents
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JudgeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipEvents(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthEvents
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipEvents(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowEvents
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowEvents
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthEvents
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupEvents
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthEvents
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthEvents        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowEvents          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupEvents = fmt.Errorf("proto: unexpected end of group")
)
