// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twilightproject/nyks/volt/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9b46f331cbb6da4, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9b46f331cbb6da4, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgSignerApplication struct {
	FragmentId     uint64 `protobuf:"varint,1,opt,name=fragmentId,proto3" json:"fragmentId,omitempty"`
	ApplicationFee uint64 `protobuf:"varint,2,opt,name=applicationFee,proto3" json:"applicationFee,omitempty"`
	FeeBips        uint64 `protobuf:"varint,3,opt,name=feeBips,proto3" json:"feeBips,omitempty"`
	BtcPubKey      string `protobuf:"bytes,4,opt,name=btcPubKey,proto3" json:"btcPubKey,omitempty"`
	SignerAddress  string `protobuf:"bytes,5,opt,name=signerAddress,proto3" json:"signerAddress,omitempty"`
}

func (m *MsgSignerApplication) Reset()         { *m = MsgSignerApplication{} }
func (m *MsgSignerApplication) String() string { return proto.CompactTextString(m) }
func (*MsgSignerApplication) ProtoMessage()    {}
func (*MsgSignerApplication) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9b46f331cbb6da4, []int{2}
}
func (m *MsgSignerApplication) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSignerApplication) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSignerApplication.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSignerApplication) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSignerApplication.Merge(m, src)
}
func (m *MsgSignerApplication) XXX_Size() int {
	return m.Size()
}
func (m *MsgSignerApplication) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSignerApplication.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSignerApplication proto.InternalMessageInfo

func (m *MsgSignerApplication) GetFragmentId() uint64 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *MsgSignerApplication) GetApplicationFee() uint64 {
	if m != nil {
		return m.ApplicationFee
	}
	return 0
}

func (m *MsgSignerApplication) GetFeeBips() uint64 {
	if m != nil {
		return m.FeeBips
	}
	return 0
}

func (m *MsgSignerApplication) GetBtcPubKey() string {
	if m != nil {
		return m.BtcPubKey
	}
	return ""
}

func (m *MsgSignerApplication) GetSignerAddress() string {
	if m != nil {
		return m.SignerAddress
	}
	return ""
}

type SignerApplicationData struct {
	ApplicationId  uint64 `protobuf:"varint,1,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
	FragmentId     uint64 `protobuf:"varint,2,opt,name=fragmentId,proto3" json:"fragmentId,omitempty"`
	ApplicationFee uint64 `protobuf:"varint,3,opt,name=applicationFee,proto3" json:"applicationFee,omitempty"`
	FeeBips        uint64 `protobuf:"varint,4,opt,name=feeBips,proto3" json:"feeBips,omitempty"`
	BtcPubKey      string `protobuf:"bytes,5,opt,name=btcPubKey,proto3" json:"btcPubKey,omitempty"`
	SignerAddress  string `protobuf:"bytes,6,opt,name=signerAddress,proto3" json:"signerAddress,omitempty"`
}

func (m *SignerApplicationData) Reset()         { *m = SignerApplicationData{} }
func (m *SignerApplicationData) String() string { return proto.CompactTextString(m) }
func (*SignerApplicationData) ProtoMessage()    {}
func (*SignerApplicationData) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9b46f331cbb6da4, []int{3}
}
func (m *SignerApplicationData) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *SignerApplicationData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_SignerApplicationData.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *SignerApplicationData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignerApplicationData.Merge(m, src)
}
func (m *SignerApplicationData) XXX_Size() int {
	return m.Size()
}
func (m *SignerApplicationData) XXX_DiscardUnknown() {
	xxx_messageInfo_SignerApplicationData.DiscardUnknown(m)
}

var xxx_messageInfo_SignerApplicationData proto.InternalMessageInfo

func (m *SignerApplicationData) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

func (m *SignerApplicationData) GetFragmentId() uint64 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *SignerApplicationData) GetApplicationFee() uint64 {
	if m != nil {
		return m.ApplicationFee
	}
	return 0
}

func (m *SignerApplicationData) GetFeeBips() uint64 {
	if m != nil {
		return m.FeeBips
	}
	return 0
}

func (m *SignerApplicationData) GetBtcPubKey() string {
	if m != nil {
		return m.BtcPubKey
	}
	return ""
}

func (m *SignerApplicationData) GetSignerAddress() string {
	if m != nil {
		return m.SignerAddress
	}
	return ""
}

type MsgSignerApplicationResponse struct {
	ApplicationId uint64 `protobuf:"varint,1,opt,name=applicationId,proto3" json:"applicationId,omitempty"`
}

func (m *MsgSignerApplicationResponse) Reset()         { *m = MsgSignerApplicationResponse{} }
func (m *MsgSignerApplicationResponse) String() string { return proto.CompactTextString(m) }
func (*MsgSignerApplicationResponse) ProtoMessage()    {}
func (*MsgSignerApplicationResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9b46f331cbb6da4, []int{4}
}
func (m *MsgSignerApplicationResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgSignerApplicationResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgSignerApplicationResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgSignerApplicationResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgSignerApplicationResponse.Merge(m, src)
}
func (m *MsgSignerApplicationResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgSignerApplicationResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgSignerApplicationResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgSignerApplicationResponse proto.InternalMessageInfo

func (m *MsgSignerApplicationResponse) GetApplicationId() uint64 {
	if m != nil {
		return m.ApplicationId
	}
	return 0
}

type MsgAcceptSigners struct {
	FragmentId           uint64   `protobuf:"varint,1,opt,name=fragmentId,proto3" json:"fragmentId,omitempty"`
	SignerApplicationIds []uint64 `protobuf:"varint,2,rep,packed,name=signerApplicationIds,proto3" json:"signerApplicationIds,omitempty"`
	JudgeAddress         string   `protobuf:"bytes,3,opt,name=judgeAddress,proto3" json:"judgeAddress,omitempty"`
}

func (m *MsgAcceptSigners) Reset()         { *m = MsgAcceptSigners{} }
func (m *MsgAcceptSigners) String() string { return proto.CompactTextString(m) }
func (*MsgAcceptSigners) ProtoMessage()    {}
func (*MsgAcceptSigners) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9b46f331cbb6da4, []int{5}
}
func (m *MsgAcceptSigners) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAcceptSigners) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAcceptSigners.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAcceptSigners) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAcceptSigners.Merge(m, src)
}
func (m *MsgAcceptSigners) XXX_Size() int {
	return m.Size()
}
func (m *MsgAcceptSigners) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAcceptSigners.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAcceptSigners proto.InternalMessageInfo

func (m *MsgAcceptSigners) GetFragmentId() uint64 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *MsgAcceptSigners) GetSignerApplicationIds() []uint64 {
	if m != nil {
		return m.SignerApplicationIds
	}
	return nil
}

func (m *MsgAcceptSigners) GetJudgeAddress() string {
	if m != nil {
		return m.JudgeAddress
	}
	return ""
}

type MsgAcceptSignersResponse struct {
}

func (m *MsgAcceptSignersResponse) Reset()         { *m = MsgAcceptSignersResponse{} }
func (m *MsgAcceptSignersResponse) String() string { return proto.CompactTextString(m) }
func (*MsgAcceptSignersResponse) ProtoMessage()    {}
func (*MsgAcceptSignersResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9b46f331cbb6da4, []int{6}
}
func (m *MsgAcceptSignersResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgAcceptSignersResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgAcceptSignersResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgAcceptSignersResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgAcceptSignersResponse.Merge(m, src)
}
func (m *MsgAcceptSignersResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgAcceptSignersResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgAcceptSignersResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgAcceptSignersResponse proto.InternalMessageInfo

type Fragment struct {
	FragmentId           uint64             `protobuf:"varint,1,opt,name=FragmentId,proto3" json:"FragmentId,omitempty"`
	FragmentStatus       bool               `protobuf:"varint,2,opt,name=FragmentStatus,proto3" json:"FragmentStatus,omitempty"`
	JudgeAddress         string             `protobuf:"bytes,3,opt,name=JudgeAddress,proto3" json:"JudgeAddress,omitempty"`
	JudgeStatus          bool               `protobuf:"varint,4,opt,name=JudgeStatus,proto3" json:"JudgeStatus,omitempty"`
	Signers              []*FragmentSigners `protobuf:"bytes,5,rep,name=Signers,proto3" json:"Signers,omitempty"`
	SignerApplicationFee uint64             `protobuf:"varint,6,opt,name=SignerApplicationFee,proto3" json:"SignerApplicationFee,omitempty"`
	Threshold            uint64             `protobuf:"varint,7,opt,name=Threshold,proto3" json:"Threshold,omitempty"`
	FeePool              uint64             `protobuf:"varint,8,opt,name=FeePool,proto3" json:"FeePool,omitempty"`
	FragmentFeeBips      uint64             `protobuf:"varint,9,opt,name=FragmentFeeBips,proto3" json:"FragmentFeeBips,omitempty"`
	ArbitraryData        string             `protobuf:"bytes,10,opt,name=arbitraryData,proto3" json:"arbitraryData,omitempty"`
	ReserveIds           []uint64           `protobuf:"varint,11,rep,packed,name=ReserveIds,proto3" json:"ReserveIds,omitempty"`
}

func (m *Fragment) Reset()         { *m = Fragment{} }
func (m *Fragment) String() string { return proto.CompactTextString(m) }
func (*Fragment) ProtoMessage()    {}
func (*Fragment) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9b46f331cbb6da4, []int{7}
}
func (m *Fragment) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *Fragment) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_Fragment.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *Fragment) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Fragment.Merge(m, src)
}
func (m *Fragment) XXX_Size() int {
	return m.Size()
}
func (m *Fragment) XXX_DiscardUnknown() {
	xxx_messageInfo_Fragment.DiscardUnknown(m)
}

var xxx_messageInfo_Fragment proto.InternalMessageInfo

func (m *Fragment) GetFragmentId() uint64 {
	if m != nil {
		return m.FragmentId
	}
	return 0
}

func (m *Fragment) GetFragmentStatus() bool {
	if m != nil {
		return m.FragmentStatus
	}
	return false
}

func (m *Fragment) GetJudgeAddress() string {
	if m != nil {
		return m.JudgeAddress
	}
	return ""
}

func (m *Fragment) GetJudgeStatus() bool {
	if m != nil {
		return m.JudgeStatus
	}
	return false
}

func (m *Fragment) GetSigners() []*FragmentSigners {
	if m != nil {
		return m.Signers
	}
	return nil
}

func (m *Fragment) GetSignerApplicationFee() uint64 {
	if m != nil {
		return m.SignerApplicationFee
	}
	return 0
}

func (m *Fragment) GetThreshold() uint64 {
	if m != nil {
		return m.Threshold
	}
	return 0
}

func (m *Fragment) GetFeePool() uint64 {
	if m != nil {
		return m.FeePool
	}
	return 0
}

func (m *Fragment) GetFragmentFeeBips() uint64 {
	if m != nil {
		return m.FragmentFeeBips
	}
	return 0
}

func (m *Fragment) GetArbitraryData() string {
	if m != nil {
		return m.ArbitraryData
	}
	return ""
}

func (m *Fragment) GetReserveIds() []uint64 {
	if m != nil {
		return m.ReserveIds
	}
	return nil
}

type FragmentSigners struct {
	FragmentID           uint64 `protobuf:"varint,1,opt,name=FragmentID,proto3" json:"FragmentID,omitempty"`
	SignerAddress        string `protobuf:"bytes,2,opt,name=SignerAddress,proto3" json:"SignerAddress,omitempty"`
	SignerStatus         bool   `protobuf:"varint,3,opt,name=SignerStatus,proto3" json:"SignerStatus,omitempty"`
	SignerBtcPublicKey   string `protobuf:"bytes,4,opt,name=SignerBtcPublicKey,proto3" json:"SignerBtcPublicKey,omitempty"`
	SignerApplicationFee uint64 `protobuf:"varint,5,opt,name=SignerApplicationFee,proto3" json:"SignerApplicationFee,omitempty"`
	SignerFeeBips        uint64 `protobuf:"varint,6,opt,name=SignerFeeBips,proto3" json:"SignerFeeBips,omitempty"`
}

func (m *FragmentSigners) Reset()         { *m = FragmentSigners{} }
func (m *FragmentSigners) String() string { return proto.CompactTextString(m) }
func (*FragmentSigners) ProtoMessage()    {}
func (*FragmentSigners) Descriptor() ([]byte, []int) {
	return fileDescriptor_f9b46f331cbb6da4, []int{8}
}
func (m *FragmentSigners) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *FragmentSigners) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_FragmentSigners.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *FragmentSigners) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FragmentSigners.Merge(m, src)
}
func (m *FragmentSigners) XXX_Size() int {
	return m.Size()
}
func (m *FragmentSigners) XXX_DiscardUnknown() {
	xxx_messageInfo_FragmentSigners.DiscardUnknown(m)
}

var xxx_messageInfo_FragmentSigners proto.InternalMessageInfo

func (m *FragmentSigners) GetFragmentID() uint64 {
	if m != nil {
		return m.FragmentID
	}
	return 0
}

func (m *FragmentSigners) GetSignerAddress() string {
	if m != nil {
		return m.SignerAddress
	}
	return ""
}

func (m *FragmentSigners) GetSignerStatus() bool {
	if m != nil {
		return m.SignerStatus
	}
	return false
}

func (m *FragmentSigners) GetSignerBtcPublicKey() string {
	if m != nil {
		return m.SignerBtcPublicKey
	}
	return ""
}

func (m *FragmentSigners) GetSignerApplicationFee() uint64 {
	if m != nil {
		return m.SignerApplicationFee
	}
	return 0
}

func (m *FragmentSigners) GetSignerFeeBips() uint64 {
	if m != nil {
		return m.SignerFeeBips
	}
	return 0
}

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "twilightproject.nyks.volt.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "twilightproject.nyks.volt.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgSignerApplication)(nil), "twilightproject.nyks.volt.MsgSignerApplication")
	proto.RegisterType((*SignerApplicationData)(nil), "twilightproject.nyks.volt.SignerApplicationData")
	proto.RegisterType((*MsgSignerApplicationResponse)(nil), "twilightproject.nyks.volt.MsgSignerApplicationResponse")
	proto.RegisterType((*MsgAcceptSigners)(nil), "twilightproject.nyks.volt.MsgAcceptSigners")
	proto.RegisterType((*MsgAcceptSignersResponse)(nil), "twilightproject.nyks.volt.MsgAcceptSignersResponse")
	proto.RegisterType((*Fragment)(nil), "twilightproject.nyks.volt.Fragment")
	proto.RegisterType((*FragmentSigners)(nil), "twilightproject.nyks.volt.FragmentSigners")
}

func init() {
	proto.RegisterFile("twilightproject/nyks/volt/tx.proto", fileDescriptor_f9b46f331cbb6da4)
}

var fileDescriptor_f9b46f331cbb6da4 = []byte{
	// 819 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x56, 0x31, 0x6f, 0xd3, 0x40,
	0x14, 0x8e, 0xe3, 0x24, 0x6d, 0x2e, 0x2d, 0xa5, 0xa7, 0xa0, 0xba, 0xa1, 0x0a, 0xc1, 0x42, 0x55,
	0x14, 0xd4, 0x58, 0xa4, 0x12, 0x48, 0x15, 0x4b, 0xa3, 0x28, 0x52, 0x41, 0x91, 0x2a, 0x07, 0x16,
	0x16, 0xe4, 0x24, 0x57, 0xc7, 0x25, 0xb1, 0x8d, 0xef, 0x52, 0x9a, 0x01, 0x09, 0x21, 0xb1, 0x30,
	0xf1, 0x07, 0xd8, 0x19, 0x3b, 0x30, 0xb1, 0xb0, 0x76, 0xac, 0x98, 0x98, 0x10, 0x6a, 0x86, 0x6e,
	0xfc, 0x06, 0x74, 0x77, 0xb6, 0x93, 0x73, 0xd2, 0xb4, 0x5d, 0xda, 0xdc, 0x77, 0xef, 0xde, 0xfb,
	0xbe, 0xfb, 0xde, 0x9d, 0x0f, 0xa8, 0xe4, 0x9d, 0xd5, 0xb3, 0xcc, 0x2e, 0x71, 0x3d, 0xe7, 0x10,
	0xb5, 0x89, 0x66, 0x0f, 0xdf, 0x60, 0xed, 0xc8, 0xe9, 0x11, 0x8d, 0x1c, 0x97, 0x5d, 0xcf, 0x21,
	0x0e, 0x5c, 0x8f, 0xc4, 0x94, 0x69, 0x4c, 0x99, 0xc6, 0xe4, 0x56, 0x8d, 0xbe, 0x65, 0x3b, 0x1a,
	0xfb, 0xcb, 0xa3, 0x73, 0x6b, 0x6d, 0x07, 0xf7, 0x1d, 0xac, 0xf5, 0xb1, 0xa9, 0x1d, 0x3d, 0xa2,
	0xff, 0xfc, 0x89, 0x75, 0x3e, 0xf1, 0x9a, 0x8d, 0x34, 0x3e, 0xf0, 0xa7, 0xb2, 0xa6, 0x63, 0x3a,
	0x1c, 0xa7, 0xbf, 0x7c, 0x74, 0xf3, 0x72, 0x6e, 0xae, 0xe1, 0x19, 0x7d, 0x7f, 0xb5, 0xfa, 0x53,
	0x02, 0x2b, 0x0d, 0x6c, 0xbe, 0x74, 0x3b, 0x06, 0x41, 0xfb, 0x6c, 0x06, 0x3e, 0x06, 0x69, 0x63,
	0x40, 0xba, 0x8e, 0x67, 0x91, 0xa1, 0x22, 0x15, 0xa4, 0x62, 0xba, 0xaa, 0xfc, 0xfa, 0xbe, 0x95,
	0xf5, 0xcb, 0xee, 0x76, 0x3a, 0x1e, 0xc2, 0xb8, 0x49, 0x3c, 0xcb, 0x36, 0xf5, 0x71, 0x28, 0xac,
	0x81, 0x14, 0xcf, 0xad, 0xc4, 0x0b, 0x52, 0x31, 0x53, 0xb9, 0x5f, 0xbe, 0x54, 0x7c, 0x99, 0x97,
	0xaa, 0xa6, 0x4f, 0xff, 0xdc, 0x8b, 0x7d, 0xbb, 0x38, 0x29, 0x49, 0xba, 0xbf, 0x76, 0xa7, 0xfc,
	0xf1, 0xe2, 0xa4, 0x34, 0xce, 0xfa, 0xf9, 0xe2, 0xa4, 0x74, 0x97, 0x91, 0x3f, 0xe6, 0xf4, 0x23,
	0x6c, 0xd5, 0x75, 0xb0, 0x16, 0x81, 0x74, 0x84, 0x5d, 0xc7, 0xc6, 0x48, 0x3d, 0x93, 0x40, 0xb6,
	0x81, 0xcd, 0xa6, 0x65, 0xda, 0xc8, 0xdb, 0x75, 0xdd, 0x9e, 0xd5, 0x36, 0x88, 0xe5, 0xd8, 0x30,
	0x0f, 0xc0, 0x81, 0x67, 0x98, 0x7d, 0x64, 0x93, 0xbd, 0x0e, 0x93, 0x98, 0xd0, 0x27, 0x10, 0xb8,
	0x09, 0x6e, 0x19, 0xe3, 0xf0, 0x3a, 0x42, 0x4c, 0x51, 0x42, 0x8f, 0xa0, 0x50, 0x01, 0x0b, 0x07,
	0x08, 0x55, 0x2d, 0x17, 0x2b, 0x32, 0x0b, 0x08, 0x86, 0x70, 0x03, 0xa4, 0x5b, 0xa4, 0xbd, 0x3f,
	0x68, 0x3d, 0x47, 0x43, 0x25, 0x41, 0xf7, 0x50, 0x1f, 0x03, 0xf0, 0x01, 0x58, 0xc6, 0x9c, 0x14,
	0xdf, 0x4b, 0x25, 0xc9, 0x22, 0x44, 0x70, 0x07, 0xd2, 0x9d, 0x10, 0x31, 0x75, 0x24, 0x81, 0x3b,
	0x53, 0x7a, 0x6a, 0x06, 0x31, 0x68, 0xce, 0x09, 0x76, 0xa1, 0x2c, 0x11, 0x8c, 0x28, 0x8f, 0x5f,
	0x43, 0xb9, 0x7c, 0x95, 0xf2, 0xc4, 0x1c, 0xe5, 0xc9, 0x2b, 0x95, 0xa7, 0x66, 0x28, 0x57, 0x6b,
	0x60, 0x63, 0x96, 0x6f, 0x81, 0xb1, 0xd7, 0xd3, 0xaa, 0x7e, 0x95, 0xc0, 0xed, 0x06, 0x36, 0x77,
	0xdb, 0x6d, 0xe4, 0x12, 0x9e, 0x0c, 0x5f, 0x69, 0x7d, 0x05, 0x64, 0x71, 0xb4, 0xee, 0x5e, 0x87,
	0xb6, 0xb4, 0x5c, 0x4c, 0xe8, 0x33, 0xe7, 0xa0, 0x0a, 0x96, 0x0e, 0x07, 0x1d, 0x13, 0x05, 0x9a,
	0x64, 0xa6, 0x49, 0xc0, 0x76, 0x56, 0xa9, 0x99, 0x02, 0xa4, 0xe6, 0x80, 0x12, 0xa5, 0x17, 0xb6,
	0xee, 0x0f, 0x19, 0x2c, 0xd6, 0x7d, 0x56, 0x94, 0x73, 0x7d, 0x8a, 0x73, 0x5d, 0x30, 0x2d, 0x18,
	0x35, 0x89, 0x41, 0x06, 0xfc, 0x00, 0x2e, 0xea, 0x11, 0x94, 0xf2, 0x7c, 0x36, 0x83, 0xe7, 0x24,
	0x06, 0x0b, 0x20, 0xc3, 0xc6, 0x7e, 0xa2, 0x04, 0x4b, 0x34, 0x09, 0xc1, 0x1a, 0x58, 0xf0, 0xd9,
	0x2a, 0xc9, 0x82, 0x5c, 0xcc, 0x54, 0x4a, 0x73, 0xce, 0x79, 0xc8, 0xc0, 0xd7, 0x17, 0x2c, 0xa5,
	0xfb, 0x3c, 0xe5, 0x2f, 0x6d, 0xb7, 0x14, 0x53, 0x37, 0x73, 0x8e, 0xb6, 0xd6, 0x8b, 0xae, 0x87,
	0x70, 0xd7, 0xe9, 0x75, 0x94, 0x05, 0x16, 0x38, 0x06, 0x68, 0x4b, 0xd6, 0x11, 0xda, 0x77, 0x9c,
	0x9e, 0xb2, 0xc8, 0x5b, 0xd2, 0x1f, 0xc2, 0x22, 0x58, 0x09, 0x78, 0xd4, 0xfd, 0xa6, 0x4d, 0xb3,
	0x88, 0x28, 0xcc, 0x1a, 0xcb, 0x6b, 0x59, 0xc4, 0x33, 0xbc, 0x21, 0x3d, 0x55, 0x0a, 0xe0, 0xed,
	0x29, 0x80, 0xd4, 0x0f, 0x1d, 0x61, 0xe4, 0x1d, 0x21, 0xda, 0x19, 0x19, 0xd6, 0x19, 0x13, 0x88,
	0xfa, 0x29, 0x3e, 0x2e, 0x38, 0xd1, 0x77, 0xa1, 0x63, 0xb5, 0x29, 0x0f, 0x6b, 0xb4, 0x72, 0x53,
	0x38, 0x18, 0x71, 0x5e, 0x59, 0x00, 0xa9, 0x83, 0x1c, 0xf0, 0xed, 0x91, 0x99, 0x3d, 0x02, 0x06,
	0xcb, 0x00, 0xf2, 0x71, 0x95, 0x9d, 0xba, 0x9e, 0xd5, 0x1e, 0xdf, 0x41, 0x33, 0x66, 0x2e, 0x75,
	0x22, 0x39, 0xc7, 0x89, 0x90, 0x6d, 0xb0, 0x9f, 0xdc, 0x36, 0x11, 0xac, 0xfc, 0x8b, 0x03, 0xb9,
	0x81, 0x4d, 0x68, 0x83, 0x25, 0xe1, 0x03, 0x33, 0xaf, 0x61, 0x22, 0x77, 0x79, 0xae, 0x72, 0xfd,
	0xd8, 0xf0, 0x7a, 0x78, 0x0f, 0x56, 0xa7, 0xef, 0x7c, 0x6d, 0x7e, 0xa2, 0xa9, 0x05, 0xb9, 0x27,
	0x37, 0x5c, 0x10, 0x96, 0x7f, 0x0b, 0x96, 0xc5, 0x3b, 0xe7, 0xe1, 0xfc, 0x4c, 0x42, 0x70, 0x6e,
	0xfb, 0x06, 0xc1, 0x41, 0xc9, 0x5c, 0xf2, 0x03, 0xfd, 0x86, 0x56, 0x9f, 0x9e, 0x9e, 0xe7, 0xa5,
	0xb3, 0xf3, 0xbc, 0xf4, 0xf7, 0x3c, 0x2f, 0x7d, 0x19, 0xe5, 0x63, 0x67, 0xa3, 0x7c, 0xec, 0xf7,
	0x28, 0x1f, 0x7b, 0x15, 0xbe, 0x55, 0xb6, 0x84, 0x07, 0x81, 0xff, 0x4d, 0x25, 0x43, 0x17, 0xe1,
	0x56, 0x8a, 0x3d, 0x09, 0xb6, 0xff, 0x07, 0x00, 0x00, 0xff, 0xff, 0x30, 0x5f, 0x4d, 0x7b, 0xd8,
	0x08, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	SignerApplication(ctx context.Context, in *MsgSignerApplication, opts ...grpc.CallOption) (*MsgSignerApplicationResponse, error)
	AcceptSigners(ctx context.Context, in *MsgAcceptSigners, opts ...grpc.CallOption) (*MsgAcceptSignersResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.volt.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) SignerApplication(ctx context.Context, in *MsgSignerApplication, opts ...grpc.CallOption) (*MsgSignerApplicationResponse, error) {
	out := new(MsgSignerApplicationResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.volt.Msg/SignerApplication", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) AcceptSigners(ctx context.Context, in *MsgAcceptSigners, opts ...grpc.CallOption) (*MsgAcceptSignersResponse, error) {
	out := new(MsgAcceptSignersResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.volt.Msg/AcceptSigners", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	SignerApplication(context.Context, *MsgSignerApplication) (*MsgSignerApplicationResponse, error)
	AcceptSigners(context.Context, *MsgAcceptSigners) (*MsgAcceptSignersResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) SignerApplication(ctx context.Context, req *MsgSignerApplication) (*MsgSignerApplicationResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SignerApplication not implemented")
}
func (*UnimplementedMsgServer) AcceptSigners(ctx context.Context, req *MsgAcceptSigners) (*MsgAcceptSignersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AcceptSigners not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.volt.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_SignerApplication_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgSignerApplication)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).SignerApplication(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.volt.Msg/SignerApplication",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).SignerApplication(ctx, req.(*MsgSignerApplication))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_AcceptSigners_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgAcceptSigners)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).AcceptSigners(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.volt.Msg/AcceptSigners",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).AcceptSigners(ctx, req.(*MsgAcceptSigners))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twilightproject.nyks.volt.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "SignerApplication",
			Handler:    _Msg_SignerApplication_Handler,
		},
		{
			MethodName: "AcceptSigners",
			Handler:    _Msg_AcceptSigners_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twilightproject/nyks/volt/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgSignerApplication) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSignerApplication) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSignerApplication) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignerAddress) > 0 {
		i -= len(m.SignerAddress)
		copy(dAtA[i:], m.SignerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignerAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.BtcPubKey) > 0 {
		i -= len(m.BtcPubKey)
		copy(dAtA[i:], m.BtcPubKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BtcPubKey)))
		i--
		dAtA[i] = 0x22
	}
	if m.FeeBips != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FeeBips))
		i--
		dAtA[i] = 0x18
	}
	if m.ApplicationFee != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ApplicationFee))
		i--
		dAtA[i] = 0x10
	}
	if m.FragmentId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FragmentId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *SignerApplicationData) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *SignerApplicationData) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *SignerApplicationData) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.SignerAddress) > 0 {
		i -= len(m.SignerAddress)
		copy(dAtA[i:], m.SignerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignerAddress)))
		i--
		dAtA[i] = 0x32
	}
	if len(m.BtcPubKey) > 0 {
		i -= len(m.BtcPubKey)
		copy(dAtA[i:], m.BtcPubKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.BtcPubKey)))
		i--
		dAtA[i] = 0x2a
	}
	if m.FeeBips != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FeeBips))
		i--
		dAtA[i] = 0x20
	}
	if m.ApplicationFee != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ApplicationFee))
		i--
		dAtA[i] = 0x18
	}
	if m.FragmentId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FragmentId))
		i--
		dAtA[i] = 0x10
	}
	if m.ApplicationId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ApplicationId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgSignerApplicationResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgSignerApplicationResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgSignerApplicationResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.ApplicationId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.ApplicationId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgAcceptSigners) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAcceptSigners) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAcceptSigners) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.JudgeAddress) > 0 {
		i -= len(m.JudgeAddress)
		copy(dAtA[i:], m.JudgeAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.JudgeAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if len(m.SignerApplicationIds) > 0 {
		dAtA3 := make([]byte, len(m.SignerApplicationIds)*10)
		var j2 int
		for _, num := range m.SignerApplicationIds {
			for num >= 1<<7 {
				dAtA3[j2] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j2++
			}
			dAtA3[j2] = uint8(num)
			j2++
		}
		i -= j2
		copy(dAtA[i:], dAtA3[:j2])
		i = encodeVarintTx(dAtA, i, uint64(j2))
		i--
		dAtA[i] = 0x12
	}
	if m.FragmentId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FragmentId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgAcceptSignersResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgAcceptSignersResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgAcceptSignersResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *Fragment) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *Fragment) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *Fragment) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ReserveIds) > 0 {
		dAtA5 := make([]byte, len(m.ReserveIds)*10)
		var j4 int
		for _, num := range m.ReserveIds {
			for num >= 1<<7 {
				dAtA5[j4] = uint8(uint64(num)&0x7f | 0x80)
				num >>= 7
				j4++
			}
			dAtA5[j4] = uint8(num)
			j4++
		}
		i -= j4
		copy(dAtA[i:], dAtA5[:j4])
		i = encodeVarintTx(dAtA, i, uint64(j4))
		i--
		dAtA[i] = 0x5a
	}
	if len(m.ArbitraryData) > 0 {
		i -= len(m.ArbitraryData)
		copy(dAtA[i:], m.ArbitraryData)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ArbitraryData)))
		i--
		dAtA[i] = 0x52
	}
	if m.FragmentFeeBips != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FragmentFeeBips))
		i--
		dAtA[i] = 0x48
	}
	if m.FeePool != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FeePool))
		i--
		dAtA[i] = 0x40
	}
	if m.Threshold != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.Threshold))
		i--
		dAtA[i] = 0x38
	}
	if m.SignerApplicationFee != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SignerApplicationFee))
		i--
		dAtA[i] = 0x30
	}
	if len(m.Signers) > 0 {
		for iNdEx := len(m.Signers) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.Signers[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintTx(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0x2a
		}
	}
	if m.JudgeStatus {
		i--
		if m.JudgeStatus {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x20
	}
	if len(m.JudgeAddress) > 0 {
		i -= len(m.JudgeAddress)
		copy(dAtA[i:], m.JudgeAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.JudgeAddress)))
		i--
		dAtA[i] = 0x1a
	}
	if m.FragmentStatus {
		i--
		if m.FragmentStatus {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x10
	}
	if m.FragmentId != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FragmentId))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *FragmentSigners) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *FragmentSigners) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *FragmentSigners) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if m.SignerFeeBips != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SignerFeeBips))
		i--
		dAtA[i] = 0x30
	}
	if m.SignerApplicationFee != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.SignerApplicationFee))
		i--
		dAtA[i] = 0x28
	}
	if len(m.SignerBtcPublicKey) > 0 {
		i -= len(m.SignerBtcPublicKey)
		copy(dAtA[i:], m.SignerBtcPublicKey)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignerBtcPublicKey)))
		i--
		dAtA[i] = 0x22
	}
	if m.SignerStatus {
		i--
		if m.SignerStatus {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x18
	}
	if len(m.SignerAddress) > 0 {
		i -= len(m.SignerAddress)
		copy(dAtA[i:], m.SignerAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.SignerAddress)))
		i--
		dAtA[i] = 0x12
	}
	if m.FragmentID != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.FragmentID))
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgSignerApplication) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FragmentId != 0 {
		n += 1 + sovTx(uint64(m.FragmentId))
	}
	if m.ApplicationFee != 0 {
		n += 1 + sovTx(uint64(m.ApplicationFee))
	}
	if m.FeeBips != 0 {
		n += 1 + sovTx(uint64(m.FeeBips))
	}
	l = len(m.BtcPubKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SignerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *SignerApplicationData) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ApplicationId != 0 {
		n += 1 + sovTx(uint64(m.ApplicationId))
	}
	if m.FragmentId != 0 {
		n += 1 + sovTx(uint64(m.FragmentId))
	}
	if m.ApplicationFee != 0 {
		n += 1 + sovTx(uint64(m.ApplicationFee))
	}
	if m.FeeBips != 0 {
		n += 1 + sovTx(uint64(m.FeeBips))
	}
	l = len(m.BtcPubKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.SignerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgSignerApplicationResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.ApplicationId != 0 {
		n += 1 + sovTx(uint64(m.ApplicationId))
	}
	return n
}

func (m *MsgAcceptSigners) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FragmentId != 0 {
		n += 1 + sovTx(uint64(m.FragmentId))
	}
	if len(m.SignerApplicationIds) > 0 {
		l = 0
		for _, e := range m.SignerApplicationIds {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	l = len(m.JudgeAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgAcceptSignersResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *Fragment) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FragmentId != 0 {
		n += 1 + sovTx(uint64(m.FragmentId))
	}
	if m.FragmentStatus {
		n += 2
	}
	l = len(m.JudgeAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.JudgeStatus {
		n += 2
	}
	if len(m.Signers) > 0 {
		for _, e := range m.Signers {
			l = e.Size()
			n += 1 + l + sovTx(uint64(l))
		}
	}
	if m.SignerApplicationFee != 0 {
		n += 1 + sovTx(uint64(m.SignerApplicationFee))
	}
	if m.Threshold != 0 {
		n += 1 + sovTx(uint64(m.Threshold))
	}
	if m.FeePool != 0 {
		n += 1 + sovTx(uint64(m.FeePool))
	}
	if m.FragmentFeeBips != 0 {
		n += 1 + sovTx(uint64(m.FragmentFeeBips))
	}
	l = len(m.ArbitraryData)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if len(m.ReserveIds) > 0 {
		l = 0
		for _, e := range m.ReserveIds {
			l += sovTx(uint64(e))
		}
		n += 1 + sovTx(uint64(l)) + l
	}
	return n
}

func (m *FragmentSigners) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.FragmentID != 0 {
		n += 1 + sovTx(uint64(m.FragmentID))
	}
	l = len(m.SignerAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SignerStatus {
		n += 2
	}
	l = len(m.SignerBtcPublicKey)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.SignerApplicationFee != 0 {
		n += 1 + sovTx(uint64(m.SignerApplicationFee))
	}
	if m.SignerFeeBips != 0 {
		n += 1 + sovTx(uint64(m.SignerFeeBips))
	}
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSignerApplication) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSignerApplication: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSignerApplication: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FragmentId", wireType)
			}
			m.FragmentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FragmentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationFee", wireType)
			}
			m.ApplicationFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApplicationFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeBips", wireType)
			}
			m.FeeBips = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeBips |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcPubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcPubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *SignerApplicationData) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: SignerApplicationData: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: SignerApplicationData: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationId", wireType)
			}
			m.ApplicationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApplicationId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FragmentId", wireType)
			}
			m.FragmentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FragmentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationFee", wireType)
			}
			m.ApplicationFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApplicationFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeeBips", wireType)
			}
			m.FeeBips = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeeBips |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcPubKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.BtcPubKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 6:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgSignerApplicationResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgSignerApplicationResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgSignerApplicationResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field ApplicationId", wireType)
			}
			m.ApplicationId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.ApplicationId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAcceptSigners) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAcceptSigners: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAcceptSigners: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FragmentId", wireType)
			}
			m.FragmentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FragmentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.SignerApplicationIds = append(m.SignerApplicationIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.SignerApplicationIds) == 0 {
					m.SignerApplicationIds = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.SignerApplicationIds = append(m.SignerApplicationIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerApplicationIds", wireType)
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JudgeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JudgeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgAcceptSignersResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgAcceptSignersResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgAcceptSignersResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *Fragment) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: Fragment: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: Fragment: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FragmentId", wireType)
			}
			m.FragmentId = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FragmentId |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FragmentStatus", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.FragmentStatus = bool(v != 0)
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field JudgeAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.JudgeAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field JudgeStatus", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.JudgeStatus = bool(v != 0)
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Signers", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Signers = append(m.Signers, &FragmentSigners{})
			if err := m.Signers[len(m.Signers)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerApplicationFee", wireType)
			}
			m.SignerApplicationFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerApplicationFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 7:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field Threshold", wireType)
			}
			m.Threshold = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.Threshold |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 8:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FeePool", wireType)
			}
			m.FeePool = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FeePool |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 9:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FragmentFeeBips", wireType)
			}
			m.FragmentFeeBips = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FragmentFeeBips |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 10:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ArbitraryData", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ArbitraryData = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 11:
			if wireType == 0 {
				var v uint64
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					v |= uint64(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				m.ReserveIds = append(m.ReserveIds, v)
			} else if wireType == 2 {
				var packedLen int
				for shift := uint(0); ; shift += 7 {
					if shift >= 64 {
						return ErrIntOverflowTx
					}
					if iNdEx >= l {
						return io.ErrUnexpectedEOF
					}
					b := dAtA[iNdEx]
					iNdEx++
					packedLen |= int(b&0x7F) << shift
					if b < 0x80 {
						break
					}
				}
				if packedLen < 0 {
					return ErrInvalidLengthTx
				}
				postIndex := iNdEx + packedLen
				if postIndex < 0 {
					return ErrInvalidLengthTx
				}
				if postIndex > l {
					return io.ErrUnexpectedEOF
				}
				var elementCount int
				var count int
				for _, integer := range dAtA[iNdEx:postIndex] {
					if integer < 128 {
						count++
					}
				}
				elementCount = count
				if elementCount != 0 && len(m.ReserveIds) == 0 {
					m.ReserveIds = make([]uint64, 0, elementCount)
				}
				for iNdEx < postIndex {
					var v uint64
					for shift := uint(0); ; shift += 7 {
						if shift >= 64 {
							return ErrIntOverflowTx
						}
						if iNdEx >= l {
							return io.ErrUnexpectedEOF
						}
						b := dAtA[iNdEx]
						iNdEx++
						v |= uint64(b&0x7F) << shift
						if b < 0x80 {
							break
						}
					}
					m.ReserveIds = append(m.ReserveIds, v)
				}
			} else {
				return fmt.Errorf("proto: wrong wireType = %d for field ReserveIds", wireType)
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *FragmentSigners) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: FragmentSigners: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: FragmentSigners: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field FragmentID", wireType)
			}
			m.FragmentID = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.FragmentID |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerStatus", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.SignerStatus = bool(v != 0)
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerBtcPublicKey", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.SignerBtcPublicKey = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerApplicationFee", wireType)
			}
			m.SignerApplicationFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerApplicationFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 6:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field SignerFeeBips", wireType)
			}
			m.SignerFeeBips = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.SignerFeeBips |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
