// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twilightproject/nyks/zkos/query.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type QueryParamsRequest struct {
}

func (m *QueryParamsRequest) Reset()         { *m = QueryParamsRequest{} }
func (m *QueryParamsRequest) String() string { return proto.CompactTextString(m) }
func (*QueryParamsRequest) ProtoMessage()    {}
func (*QueryParamsRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4347613f0a153373, []int{0}
}
func (m *QueryParamsRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsRequest.Merge(m, src)
}
func (m *QueryParamsRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsRequest proto.InternalMessageInfo

type QueryParamsResponse struct {
	Params Params `protobuf:"bytes,1,opt,name=params,proto3" json:"params"`
}

func (m *QueryParamsResponse) Reset()         { *m = QueryParamsResponse{} }
func (m *QueryParamsResponse) String() string { return proto.CompactTextString(m) }
func (*QueryParamsResponse) ProtoMessage()    {}
func (*QueryParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4347613f0a153373, []int{1}
}
func (m *QueryParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryParamsResponse.Merge(m, src)
}
func (m *QueryParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryParamsResponse proto.InternalMessageInfo

func (m *QueryParamsResponse) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type QueryTransferTxRequest struct {
	TxId string `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
}

func (m *QueryTransferTxRequest) Reset()         { *m = QueryTransferTxRequest{} }
func (m *QueryTransferTxRequest) String() string { return proto.CompactTextString(m) }
func (*QueryTransferTxRequest) ProtoMessage()    {}
func (*QueryTransferTxRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4347613f0a153373, []int{2}
}
func (m *QueryTransferTxRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTransferTxRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTransferTxRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTransferTxRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTransferTxRequest.Merge(m, src)
}
func (m *QueryTransferTxRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryTransferTxRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTransferTxRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTransferTxRequest proto.InternalMessageInfo

func (m *QueryTransferTxRequest) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

type QueryTransferTxResponse struct {
	TransferTx MsgTransferTx `protobuf:"bytes,1,opt,name=TransferTx,proto3" json:"TransferTx"`
}

func (m *QueryTransferTxResponse) Reset()         { *m = QueryTransferTxResponse{} }
func (m *QueryTransferTxResponse) String() string { return proto.CompactTextString(m) }
func (*QueryTransferTxResponse) ProtoMessage()    {}
func (*QueryTransferTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4347613f0a153373, []int{3}
}
func (m *QueryTransferTxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryTransferTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryTransferTxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryTransferTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryTransferTxResponse.Merge(m, src)
}
func (m *QueryTransferTxResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryTransferTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryTransferTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryTransferTxResponse proto.InternalMessageInfo

func (m *QueryTransferTxResponse) GetTransferTx() MsgTransferTx {
	if m != nil {
		return m.TransferTx
	}
	return MsgTransferTx{}
}

type QueryMintOrBurnTradingBtcRequest struct {
	TwilightAddress string `protobuf:"bytes,1,opt,name=twilightAddress,proto3" json:"twilightAddress,omitempty"`
}

func (m *QueryMintOrBurnTradingBtcRequest) Reset()         { *m = QueryMintOrBurnTradingBtcRequest{} }
func (m *QueryMintOrBurnTradingBtcRequest) String() string { return proto.CompactTextString(m) }
func (*QueryMintOrBurnTradingBtcRequest) ProtoMessage()    {}
func (*QueryMintOrBurnTradingBtcRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_4347613f0a153373, []int{4}
}
func (m *QueryMintOrBurnTradingBtcRequest) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMintOrBurnTradingBtcRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMintOrBurnTradingBtcRequest.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMintOrBurnTradingBtcRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMintOrBurnTradingBtcRequest.Merge(m, src)
}
func (m *QueryMintOrBurnTradingBtcRequest) XXX_Size() int {
	return m.Size()
}
func (m *QueryMintOrBurnTradingBtcRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMintOrBurnTradingBtcRequest.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMintOrBurnTradingBtcRequest proto.InternalMessageInfo

func (m *QueryMintOrBurnTradingBtcRequest) GetTwilightAddress() string {
	if m != nil {
		return m.TwilightAddress
	}
	return ""
}

type QueryMintOrBurnTradingBtcResponse struct {
	MintOrBurnTradingBtc []MsgMintBurnTradingBtc `protobuf:"bytes,1,rep,name=MintOrBurnTradingBtc,proto3" json:"MintOrBurnTradingBtc"`
}

func (m *QueryMintOrBurnTradingBtcResponse) Reset()         { *m = QueryMintOrBurnTradingBtcResponse{} }
func (m *QueryMintOrBurnTradingBtcResponse) String() string { return proto.CompactTextString(m) }
func (*QueryMintOrBurnTradingBtcResponse) ProtoMessage()    {}
func (*QueryMintOrBurnTradingBtcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_4347613f0a153373, []int{5}
}
func (m *QueryMintOrBurnTradingBtcResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *QueryMintOrBurnTradingBtcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_QueryMintOrBurnTradingBtcResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *QueryMintOrBurnTradingBtcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_QueryMintOrBurnTradingBtcResponse.Merge(m, src)
}
func (m *QueryMintOrBurnTradingBtcResponse) XXX_Size() int {
	return m.Size()
}
func (m *QueryMintOrBurnTradingBtcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_QueryMintOrBurnTradingBtcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_QueryMintOrBurnTradingBtcResponse proto.InternalMessageInfo

func (m *QueryMintOrBurnTradingBtcResponse) GetMintOrBurnTradingBtc() []MsgMintBurnTradingBtc {
	if m != nil {
		return m.MintOrBurnTradingBtc
	}
	return nil
}

func init() {
	proto.RegisterType((*QueryParamsRequest)(nil), "twilightproject.nyks.zkos.QueryParamsRequest")
	proto.RegisterType((*QueryParamsResponse)(nil), "twilightproject.nyks.zkos.QueryParamsResponse")
	proto.RegisterType((*QueryTransferTxRequest)(nil), "twilightproject.nyks.zkos.QueryTransferTxRequest")
	proto.RegisterType((*QueryTransferTxResponse)(nil), "twilightproject.nyks.zkos.QueryTransferTxResponse")
	proto.RegisterType((*QueryMintOrBurnTradingBtcRequest)(nil), "twilightproject.nyks.zkos.QueryMintOrBurnTradingBtcRequest")
	proto.RegisterType((*QueryMintOrBurnTradingBtcResponse)(nil), "twilightproject.nyks.zkos.QueryMintOrBurnTradingBtcResponse")
}

func init() {
	proto.RegisterFile("twilightproject/nyks/zkos/query.proto", fileDescriptor_4347613f0a153373)
}

var fileDescriptor_4347613f0a153373 = []byte{
	// 523 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x94, 0xc1, 0x6a, 0x13, 0x41,
	0x18, 0xc7, 0x33, 0x1a, 0x03, 0x9d, 0x1e, 0xc4, 0x31, 0x68, 0x5d, 0x64, 0x4d, 0x07, 0x95, 0x50,
	0xec, 0x4e, 0x8d, 0xe0, 0xc5, 0x5e, 0x5c, 0x44, 0x14, 0x6c, 0xd5, 0x90, 0x93, 0x1e, 0x96, 0x4d,
	0x32, 0xae, 0xd3, 0x36, 0x33, 0xdb, 0x99, 0x09, 0x6e, 0x2c, 0xbd, 0xf8, 0x02, 0x0a, 0x7d, 0x09,
	0xc1, 0x83, 0x3e, 0x46, 0x8f, 0x05, 0x2f, 0x9e, 0x44, 0x13, 0xc1, 0xd7, 0x90, 0x9d, 0x9d, 0xd0,
	0x36, 0xc9, 0x6e, 0xd4, 0x4b, 0x18, 0xbe, 0xf9, 0xff, 0xbf, 0xef, 0xf7, 0xcf, 0x7c, 0x2c, 0xbc,
	0xa1, 0xdf, 0xb0, 0x1d, 0x16, 0xbd, 0xd6, 0xb1, 0x14, 0x5b, 0xb4, 0xa3, 0x09, 0x1f, 0x6c, 0x2b,
	0xf2, 0x76, 0x5b, 0x28, 0xb2, 0xdb, 0xa7, 0x72, 0xe0, 0xc5, 0x52, 0x68, 0x81, 0xae, 0x4c, 0xc8,
	0xbc, 0x54, 0xe6, 0xa5, 0x32, 0xe7, 0x42, 0xd8, 0x63, 0x5c, 0x10, 0xf3, 0x9b, 0xa9, 0x9d, 0x6a,
	0x24, 0x22, 0x61, 0x8e, 0x24, 0x3d, 0xd9, 0xea, 0xd5, 0x48, 0x88, 0x68, 0x87, 0x92, 0x30, 0x66,
	0x24, 0xe4, 0x5c, 0xe8, 0x50, 0x33, 0xc1, 0x95, 0xbd, 0xbd, 0x99, 0x0f, 0x12, 0x87, 0x32, 0xec,
	0x8d, 0x75, 0x38, 0x5f, 0xa7, 0x93, 0x4c, 0x83, 0xab, 0x10, 0x3d, 0x4f, 0xe1, 0x9f, 0x19, 0x63,
	0x93, 0xee, 0xf6, 0xa9, 0xd2, 0xf8, 0x25, 0xbc, 0x78, 0xaa, 0xaa, 0x62, 0xc1, 0x15, 0x45, 0x0f,
	0x60, 0x25, 0x1b, 0xb0, 0x04, 0x6a, 0xa0, 0xbe, 0xd8, 0x58, 0xf6, 0x72, 0xb3, 0x7a, 0x99, 0xd5,
	0x5f, 0x38, 0xfc, 0x7e, 0xad, 0xf4, 0xf1, 0xf7, 0x97, 0x15, 0xd0, 0xb4, 0x5e, 0x7c, 0x0b, 0x5e,
	0x32, 0xcd, 0x5b, 0x32, 0xe4, 0xea, 0x15, 0x95, 0xad, 0xc4, 0x8e, 0x45, 0x08, 0x96, 0x75, 0xf2,
	0xb8, 0x6b, 0xba, 0x2f, 0x34, 0xcd, 0x19, 0x33, 0x78, 0x79, 0x4a, 0x6d, 0x71, 0x36, 0x21, 0x3c,
	0xae, 0x5a, 0xa4, 0x7a, 0x01, 0xd2, 0x86, 0x8a, 0x8e, 0xf5, 0x7e, 0x39, 0x25, 0x6b, 0x9e, 0xe8,
	0x80, 0x9f, 0xc0, 0x9a, 0x19, 0xb5, 0xc1, 0xb8, 0x7e, 0x2a, 0xfd, 0xbe, 0xe4, 0x2d, 0x19, 0x76,
	0x19, 0x8f, 0x7c, 0xdd, 0x19, 0x23, 0xd6, 0xe1, 0xf9, 0xf1, 0x80, 0xfb, 0xdd, 0xae, 0xa4, 0x4a,
	0x59, 0xda, 0xc9, 0x32, 0x7e, 0x0f, 0xe0, 0x72, 0x41, 0x3b, 0x9b, 0x61, 0x0b, 0x56, 0x67, 0xdd,
	0x2f, 0x81, 0xda, 0xd9, 0xfa, 0x62, 0x63, 0xad, 0x38, 0x4d, 0xea, 0x3c, 0xed, 0xb3, 0xa9, 0x66,
	0xf6, 0x6c, 0x7c, 0x2e, 0xc3, 0x73, 0x86, 0x08, 0x1d, 0x00, 0x58, 0xc9, 0x1e, 0x08, 0xad, 0x16,
	0x8c, 0x98, 0xde, 0x0c, 0xc7, 0xfb, 0x5b, 0x79, 0x96, 0x0f, 0xaf, 0xbc, 0xfb, 0xfa, 0xeb, 0xe0,
	0xcc, 0x75, 0x84, 0xc9, 0xd8, 0xb7, 0x9a, 0xb7, 0xb5, 0xe8, 0x13, 0x38, 0xf9, 0xa0, 0xe8, 0xf6,
	0xbc, 0x51, 0x53, 0x0b, 0xe4, 0x34, 0xfe, 0xc5, 0x62, 0x09, 0xef, 0x1a, 0xc2, 0x35, 0xe4, 0x15,
	0x11, 0x6a, 0xeb, 0x0b, 0x74, 0x42, 0xf6, 0xd2, 0xbd, 0xdc, 0x47, 0x3f, 0xc1, 0xec, 0xa7, 0x43,
	0xf7, 0xe6, 0x41, 0x14, 0xec, 0x97, 0xb3, 0xfe, 0x7f, 0x66, 0x9b, 0x65, 0xd3, 0x64, 0x79, 0x84,
	0x1e, 0x16, 0x65, 0xe9, 0x31, 0xae, 0x03, 0x21, 0x83, 0x76, 0x5f, 0xf2, 0x40, 0x67, 0x4d, 0x82,
	0xb6, 0xee, 0x90, 0xbd, 0x89, 0x15, 0xde, 0xf7, 0xd7, 0x0f, 0x87, 0x2e, 0x38, 0x1a, 0xba, 0xe0,
	0xc7, 0xd0, 0x05, 0x1f, 0x46, 0x6e, 0xe9, 0x68, 0xe4, 0x96, 0xbe, 0x8d, 0xdc, 0xd2, 0x0b, 0x3c,
	0x7b, 0x40, 0x62, 0xff, 0xae, 0x41, 0x4c, 0x55, 0xbb, 0x62, 0x3e, 0x31, 0x77, 0xfe, 0x04, 0x00,
	0x00, 0xff, 0xff, 0x41, 0xe2, 0x66, 0xab, 0x39, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type QueryClient interface {
	Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error)
	TransferTx(ctx context.Context, in *QueryTransferTxRequest, opts ...grpc.CallOption) (*QueryTransferTxResponse, error)
	MintOrBurnTradingBtc(ctx context.Context, in *QueryMintOrBurnTradingBtcRequest, opts ...grpc.CallOption) (*QueryMintOrBurnTradingBtcResponse, error)
}

type queryClient struct {
	cc grpc1.ClientConn
}

func NewQueryClient(cc grpc1.ClientConn) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) Params(ctx context.Context, in *QueryParamsRequest, opts ...grpc.CallOption) (*QueryParamsResponse, error) {
	out := new(QueryParamsResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.zkos.Query/Params", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) TransferTx(ctx context.Context, in *QueryTransferTxRequest, opts ...grpc.CallOption) (*QueryTransferTxResponse, error) {
	out := new(QueryTransferTxResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.zkos.Query/TransferTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) MintOrBurnTradingBtc(ctx context.Context, in *QueryMintOrBurnTradingBtcRequest, opts ...grpc.CallOption) (*QueryMintOrBurnTradingBtcResponse, error) {
	out := new(QueryMintOrBurnTradingBtcResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.zkos.Query/MintOrBurnTradingBtc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueryServer is the server API for Query service.
type QueryServer interface {
	Params(context.Context, *QueryParamsRequest) (*QueryParamsResponse, error)
	TransferTx(context.Context, *QueryTransferTxRequest) (*QueryTransferTxResponse, error)
	MintOrBurnTradingBtc(context.Context, *QueryMintOrBurnTradingBtcRequest) (*QueryMintOrBurnTradingBtcResponse, error)
}

// UnimplementedQueryServer can be embedded to have forward compatible implementations.
type UnimplementedQueryServer struct {
}

func (*UnimplementedQueryServer) Params(ctx context.Context, req *QueryParamsRequest) (*QueryParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Params not implemented")
}
func (*UnimplementedQueryServer) TransferTx(ctx context.Context, req *QueryTransferTxRequest) (*QueryTransferTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferTx not implemented")
}
func (*UnimplementedQueryServer) MintOrBurnTradingBtc(ctx context.Context, req *QueryMintOrBurnTradingBtcRequest) (*QueryMintOrBurnTradingBtcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintOrBurnTradingBtc not implemented")
}

func RegisterQueryServer(s grpc1.Server, srv QueryServer) {
	s.RegisterService(&_Query_serviceDesc, srv)
}

func _Query_Params_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryParamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).Params(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.zkos.Query/Params",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).Params(ctx, req.(*QueryParamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_TransferTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryTransferTxRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).TransferTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.zkos.Query/TransferTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).TransferTx(ctx, req.(*QueryTransferTxRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_MintOrBurnTradingBtc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMintOrBurnTradingBtcRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).MintOrBurnTradingBtc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.zkos.Query/MintOrBurnTradingBtc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).MintOrBurnTradingBtc(ctx, req.(*QueryMintOrBurnTradingBtcRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var Query_serviceDesc = _Query_serviceDesc
var _Query_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twilightproject.nyks.zkos.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Params",
			Handler:    _Query_Params_Handler,
		},
		{
			MethodName: "TransferTx",
			Handler:    _Query_TransferTx_Handler,
		},
		{
			MethodName: "MintOrBurnTradingBtc",
			Handler:    _Query_MintOrBurnTradingBtc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twilightproject/nyks/zkos/query.proto",
}

func (m *QueryParamsRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *QueryParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryTransferTxRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTransferTxRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTransferTxRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TxId) > 0 {
		i -= len(m.TxId)
		copy(dAtA[i:], m.TxId)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TxId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryTransferTxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryTransferTxResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryTransferTxResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.TransferTx.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintQuery(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0xa
	return len(dAtA) - i, nil
}

func (m *QueryMintOrBurnTradingBtcRequest) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMintOrBurnTradingBtcRequest) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMintOrBurnTradingBtcRequest) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TwilightAddress) > 0 {
		i -= len(m.TwilightAddress)
		copy(dAtA[i:], m.TwilightAddress)
		i = encodeVarintQuery(dAtA, i, uint64(len(m.TwilightAddress)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *QueryMintOrBurnTradingBtcResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *QueryMintOrBurnTradingBtcResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *QueryMintOrBurnTradingBtcResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.MintOrBurnTradingBtc) > 0 {
		for iNdEx := len(m.MintOrBurnTradingBtc) - 1; iNdEx >= 0; iNdEx-- {
			{
				size, err := m.MintOrBurnTradingBtc[iNdEx].MarshalToSizedBuffer(dAtA[:i])
				if err != nil {
					return 0, err
				}
				i -= size
				i = encodeVarintQuery(dAtA, i, uint64(size))
			}
			i--
			dAtA[i] = 0xa
		}
	}
	return len(dAtA) - i, nil
}

func encodeVarintQuery(dAtA []byte, offset int, v uint64) int {
	offset -= sovQuery(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *QueryParamsRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *QueryParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.Params.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryTransferTxRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxId)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryTransferTxResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = m.TransferTx.Size()
	n += 1 + l + sovQuery(uint64(l))
	return n
}

func (m *QueryMintOrBurnTradingBtcRequest) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TwilightAddress)
	if l > 0 {
		n += 1 + l + sovQuery(uint64(l))
	}
	return n
}

func (m *QueryMintOrBurnTradingBtcResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if len(m.MintOrBurnTradingBtc) > 0 {
		for _, e := range m.MintOrBurnTradingBtc {
			l = e.Size()
			n += 1 + l + sovQuery(uint64(l))
		}
	}
	return n
}

func sovQuery(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozQuery(x uint64) (n int) {
	return sovQuery(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *QueryParamsRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTransferTxRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTransferTxRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTransferTxRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryTransferTxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryTransferTxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryTransferTxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TransferTx", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.TransferTx.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMintOrBurnTradingBtcRequest) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMintOrBurnTradingBtcRequest: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMintOrBurnTradingBtcRequest: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwilightAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TwilightAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *QueryMintOrBurnTradingBtcResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: QueryMintOrBurnTradingBtcResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: QueryMintOrBurnTradingBtcResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintOrBurnTradingBtc", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthQuery
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthQuery
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.MintOrBurnTradingBtc = append(m.MintOrBurnTradingBtc, MsgMintBurnTradingBtc{})
			if err := m.MintOrBurnTradingBtc[len(m.MintOrBurnTradingBtc)-1].Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipQuery(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthQuery
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipQuery(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowQuery
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowQuery
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthQuery
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupQuery
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthQuery
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthQuery        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowQuery          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupQuery = fmt.Errorf("proto: unexpected end of group")
)
