// Code generated by protoc-gen-gogo. DO NOT EDIT.
// source: twilightproject/nyks/zkos/tx.proto

package types

import (
	context "context"
	fmt "fmt"
	_ "github.com/cosmos/cosmos-proto"
	_ "github.com/cosmos/cosmos-sdk/types/msgservice"
	_ "github.com/cosmos/cosmos-sdk/types/tx/amino"
	_ "github.com/cosmos/gogoproto/gogoproto"
	grpc1 "github.com/cosmos/gogoproto/grpc"
	proto "github.com/cosmos/gogoproto/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	io "io"
	math "math"
	math_bits "math/bits"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.GoGoProtoPackageIsVersion3 // please upgrade the proto package

type MsgUpdateParams struct {
	Authority string `protobuf:"bytes,1,opt,name=authority,proto3" json:"authority,omitempty"`
	Params    Params `protobuf:"bytes,2,opt,name=params,proto3" json:"params"`
}

func (m *MsgUpdateParams) Reset()         { *m = MsgUpdateParams{} }
func (m *MsgUpdateParams) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParams) ProtoMessage()    {}
func (*MsgUpdateParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_012d1c47f369bccb, []int{0}
}
func (m *MsgUpdateParams) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParams.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParams.Merge(m, src)
}
func (m *MsgUpdateParams) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParams) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParams.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParams proto.InternalMessageInfo

func (m *MsgUpdateParams) GetAuthority() string {
	if m != nil {
		return m.Authority
	}
	return ""
}

func (m *MsgUpdateParams) GetParams() Params {
	if m != nil {
		return m.Params
	}
	return Params{}
}

type MsgUpdateParamsResponse struct {
}

func (m *MsgUpdateParamsResponse) Reset()         { *m = MsgUpdateParamsResponse{} }
func (m *MsgUpdateParamsResponse) String() string { return proto.CompactTextString(m) }
func (*MsgUpdateParamsResponse) ProtoMessage()    {}
func (*MsgUpdateParamsResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_012d1c47f369bccb, []int{1}
}
func (m *MsgUpdateParamsResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgUpdateParamsResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgUpdateParamsResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgUpdateParamsResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgUpdateParamsResponse.Merge(m, src)
}
func (m *MsgUpdateParamsResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgUpdateParamsResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgUpdateParamsResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgUpdateParamsResponse proto.InternalMessageInfo

type MsgTransferTx struct {
	TxId            string `protobuf:"bytes,1,opt,name=txId,proto3" json:"txId,omitempty"`
	TxByteCode      string `protobuf:"bytes,2,opt,name=txByteCode,proto3" json:"txByteCode,omitempty"`
	TxFee           uint64 `protobuf:"varint,3,opt,name=txFee,proto3" json:"txFee,omitempty"`
	ZkOracleAddress string `protobuf:"bytes,4,opt,name=zkOracleAddress,proto3" json:"zkOracleAddress,omitempty"`
}

func (m *MsgTransferTx) Reset()         { *m = MsgTransferTx{} }
func (m *MsgTransferTx) String() string { return proto.CompactTextString(m) }
func (*MsgTransferTx) ProtoMessage()    {}
func (*MsgTransferTx) Descriptor() ([]byte, []int) {
	return fileDescriptor_012d1c47f369bccb, []int{2}
}
func (m *MsgTransferTx) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferTx) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferTx.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferTx) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferTx.Merge(m, src)
}
func (m *MsgTransferTx) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferTx) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferTx.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferTx proto.InternalMessageInfo

func (m *MsgTransferTx) GetTxId() string {
	if m != nil {
		return m.TxId
	}
	return ""
}

func (m *MsgTransferTx) GetTxByteCode() string {
	if m != nil {
		return m.TxByteCode
	}
	return ""
}

func (m *MsgTransferTx) GetTxFee() uint64 {
	if m != nil {
		return m.TxFee
	}
	return 0
}

func (m *MsgTransferTx) GetZkOracleAddress() string {
	if m != nil {
		return m.ZkOracleAddress
	}
	return ""
}

type MsgTransferTxResponse struct {
}

func (m *MsgTransferTxResponse) Reset()         { *m = MsgTransferTxResponse{} }
func (m *MsgTransferTxResponse) String() string { return proto.CompactTextString(m) }
func (*MsgTransferTxResponse) ProtoMessage()    {}
func (*MsgTransferTxResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_012d1c47f369bccb, []int{3}
}
func (m *MsgTransferTxResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgTransferTxResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgTransferTxResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgTransferTxResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgTransferTxResponse.Merge(m, src)
}
func (m *MsgTransferTxResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgTransferTxResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgTransferTxResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgTransferTxResponse proto.InternalMessageInfo

type MsgMintBurnTradingBtc struct {
	MintOrBurn      bool   `protobuf:"varint,1,opt,name=mintOrBurn,proto3" json:"mintOrBurn,omitempty"`
	BtcValue        uint64 `protobuf:"varint,2,opt,name=btcValue,proto3" json:"btcValue,omitempty"`
	QqAccount       string `protobuf:"bytes,3,opt,name=qqAccount,proto3" json:"qqAccount,omitempty"`
	EncryptScalar   string `protobuf:"bytes,4,opt,name=encryptScalar,proto3" json:"encryptScalar,omitempty"`
	TwilightAddress string `protobuf:"bytes,5,opt,name=twilightAddress,proto3" json:"twilightAddress,omitempty"`
}

func (m *MsgMintBurnTradingBtc) Reset()         { *m = MsgMintBurnTradingBtc{} }
func (m *MsgMintBurnTradingBtc) String() string { return proto.CompactTextString(m) }
func (*MsgMintBurnTradingBtc) ProtoMessage()    {}
func (*MsgMintBurnTradingBtc) Descriptor() ([]byte, []int) {
	return fileDescriptor_012d1c47f369bccb, []int{4}
}
func (m *MsgMintBurnTradingBtc) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMintBurnTradingBtc) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMintBurnTradingBtc.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMintBurnTradingBtc) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintBurnTradingBtc.Merge(m, src)
}
func (m *MsgMintBurnTradingBtc) XXX_Size() int {
	return m.Size()
}
func (m *MsgMintBurnTradingBtc) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintBurnTradingBtc.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintBurnTradingBtc proto.InternalMessageInfo

func (m *MsgMintBurnTradingBtc) GetMintOrBurn() bool {
	if m != nil {
		return m.MintOrBurn
	}
	return false
}

func (m *MsgMintBurnTradingBtc) GetBtcValue() uint64 {
	if m != nil {
		return m.BtcValue
	}
	return 0
}

func (m *MsgMintBurnTradingBtc) GetQqAccount() string {
	if m != nil {
		return m.QqAccount
	}
	return ""
}

func (m *MsgMintBurnTradingBtc) GetEncryptScalar() string {
	if m != nil {
		return m.EncryptScalar
	}
	return ""
}

func (m *MsgMintBurnTradingBtc) GetTwilightAddress() string {
	if m != nil {
		return m.TwilightAddress
	}
	return ""
}

type MsgMintBurnTradingBtcResponse struct {
}

func (m *MsgMintBurnTradingBtcResponse) Reset()         { *m = MsgMintBurnTradingBtcResponse{} }
func (m *MsgMintBurnTradingBtcResponse) String() string { return proto.CompactTextString(m) }
func (*MsgMintBurnTradingBtcResponse) ProtoMessage()    {}
func (*MsgMintBurnTradingBtcResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_012d1c47f369bccb, []int{5}
}
func (m *MsgMintBurnTradingBtcResponse) XXX_Unmarshal(b []byte) error {
	return m.Unmarshal(b)
}
func (m *MsgMintBurnTradingBtcResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	if deterministic {
		return xxx_messageInfo_MsgMintBurnTradingBtcResponse.Marshal(b, m, deterministic)
	} else {
		b = b[:cap(b)]
		n, err := m.MarshalToSizedBuffer(b)
		if err != nil {
			return nil, err
		}
		return b[:n], nil
	}
}
func (m *MsgMintBurnTradingBtcResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MsgMintBurnTradingBtcResponse.Merge(m, src)
}
func (m *MsgMintBurnTradingBtcResponse) XXX_Size() int {
	return m.Size()
}
func (m *MsgMintBurnTradingBtcResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_MsgMintBurnTradingBtcResponse.DiscardUnknown(m)
}

var xxx_messageInfo_MsgMintBurnTradingBtcResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*MsgUpdateParams)(nil), "twilightproject.nyks.zkos.MsgUpdateParams")
	proto.RegisterType((*MsgUpdateParamsResponse)(nil), "twilightproject.nyks.zkos.MsgUpdateParamsResponse")
	proto.RegisterType((*MsgTransferTx)(nil), "twilightproject.nyks.zkos.MsgTransferTx")
	proto.RegisterType((*MsgTransferTxResponse)(nil), "twilightproject.nyks.zkos.MsgTransferTxResponse")
	proto.RegisterType((*MsgMintBurnTradingBtc)(nil), "twilightproject.nyks.zkos.MsgMintBurnTradingBtc")
	proto.RegisterType((*MsgMintBurnTradingBtcResponse)(nil), "twilightproject.nyks.zkos.MsgMintBurnTradingBtcResponse")
}

func init() {
	proto.RegisterFile("twilightproject/nyks/zkos/tx.proto", fileDescriptor_012d1c47f369bccb)
}

var fileDescriptor_012d1c47f369bccb = []byte{
	// 587 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xbf, 0x6f, 0xd3, 0x40,
	0x14, 0xce, 0xb5, 0x69, 0x55, 0x1f, 0x54, 0x15, 0xa7, 0xa0, 0x24, 0x06, 0xdc, 0x60, 0x21, 0x14,
	0x45, 0xaa, 0x0d, 0x41, 0x42, 0xa8, 0x62, 0xa9, 0x41, 0x48, 0x0c, 0x51, 0x91, 0x1b, 0x18, 0x58,
	0x90, 0x6b, 0x1f, 0x8e, 0x49, 0x72, 0xe7, 0xde, 0x5d, 0xc0, 0xe9, 0x54, 0x31, 0x32, 0xb1, 0xf2,
	0x1f, 0x30, 0x66, 0x60, 0x67, 0xed, 0x58, 0xb1, 0xc0, 0x84, 0x50, 0x32, 0x44, 0xfc, 0x17, 0xc8,
	0x3e, 0xe7, 0x97, 0x69, 0x4b, 0x59, 0x92, 0x7b, 0xdf, 0xfb, 0xde, 0x7b, 0xdf, 0xe7, 0xfb, 0x01,
	0x75, 0xf1, 0x2e, 0xe8, 0x04, 0x7e, 0x4b, 0x84, 0x8c, 0xbe, 0xc1, 0xae, 0x30, 0x49, 0xbf, 0xcd,
	0xcd, 0xc3, 0x36, 0xe5, 0xa6, 0x88, 0x8c, 0x90, 0x51, 0x41, 0x51, 0x39, 0xc3, 0x31, 0x62, 0x8e,
	0x11, 0x73, 0xd4, 0x2b, 0x4e, 0x37, 0x20, 0xd4, 0x4c, 0x7e, 0x25, 0x5b, 0x2d, 0xba, 0x94, 0x77,
	0x29, 0x37, 0xbb, 0xdc, 0x37, 0xdf, 0xde, 0x8d, 0xff, 0xd2, 0x44, 0x59, 0x26, 0x5e, 0x25, 0x91,
	0x29, 0x83, 0x34, 0x55, 0xf0, 0xa9, 0x4f, 0x25, 0x1e, 0xaf, 0x52, 0xf4, 0xf6, 0xd9, 0xda, 0x42,
	0x87, 0x39, 0xdd, 0xb4, 0x5a, 0xff, 0x0a, 0xe0, 0x46, 0x83, 0xfb, 0xcf, 0x43, 0xcf, 0x11, 0xf8,
	0x59, 0x92, 0x41, 0xf7, 0xa1, 0xe2, 0xf4, 0x44, 0x8b, 0xb2, 0x40, 0xf4, 0x4b, 0xa0, 0x02, 0xaa,
	0x8a, 0x55, 0xfa, 0xf6, 0x65, 0xab, 0x90, 0x8e, 0xdd, 0xf1, 0x3c, 0x86, 0x39, 0xdf, 0x13, 0x2c,
	0x20, 0xbe, 0x3d, 0xa3, 0xa2, 0xc7, 0x70, 0x55, 0xf6, 0x2e, 0x2d, 0x55, 0x40, 0xf5, 0x52, 0xfd,
	0xa6, 0x71, 0xa6, 0x79, 0x43, 0x8e, 0xb2, 0x94, 0xe3, 0x9f, 0x9b, 0xb9, 0xcf, 0xe3, 0x41, 0x0d,
	0xd8, 0x69, 0xed, 0xb6, 0xf1, 0x7e, 0x3c, 0xa8, 0xcd, 0xba, 0x7e, 0x18, 0x0f, 0x6a, 0xd7, 0x12,
	0xf1, 0x91, 0x94, 0x9f, 0x51, 0xab, 0x97, 0x61, 0x31, 0x03, 0xd9, 0x98, 0x87, 0x94, 0x70, 0xac,
	0x7f, 0x02, 0x70, 0xbd, 0xc1, 0xfd, 0x26, 0x73, 0x08, 0x7f, 0x8d, 0x59, 0x33, 0x42, 0x08, 0xe6,
	0x45, 0xf4, 0xd4, 0x93, 0xae, 0xec, 0x64, 0x8d, 0x34, 0x08, 0x45, 0x64, 0xf5, 0x05, 0x7e, 0x44,
	0x3d, 0x9c, 0x48, 0x57, 0xec, 0x39, 0x04, 0x15, 0xe0, 0x8a, 0x88, 0x9e, 0x60, 0x5c, 0x5a, 0xae,
	0x80, 0x6a, 0xde, 0x96, 0x01, 0xaa, 0xc2, 0x8d, 0xc3, 0xf6, 0x2e, 0x73, 0xdc, 0x0e, 0x4e, 0x3f,
	0x48, 0x29, 0x9f, 0x94, 0x66, 0xe1, 0xed, 0x42, 0x6c, 0x28, 0x8b, 0xea, 0x45, 0x78, 0x75, 0x41,
	0xda, 0x54, 0xf4, 0x77, 0x90, 0x64, 0x1a, 0x01, 0x11, 0x56, 0x8f, 0x91, 0x26, 0x73, 0xbc, 0x80,
	0xf8, 0x96, 0x70, 0x63, 0xa1, 0xdd, 0x80, 0x88, 0x5d, 0x16, 0xe3, 0x89, 0x85, 0x35, 0x7b, 0x0e,
	0x41, 0x2a, 0x5c, 0xdb, 0x17, 0xee, 0x0b, 0xa7, 0xd3, 0x93, 0x36, 0xf2, 0xf6, 0x34, 0x46, 0xd7,
	0xa1, 0x72, 0x70, 0xb0, 0xe3, 0xba, 0xb4, 0x47, 0x44, 0x62, 0x44, 0xb1, 0x67, 0x00, 0xba, 0x05,
	0xd7, 0x31, 0x71, 0x59, 0x3f, 0x14, 0x7b, 0xae, 0xd3, 0x71, 0x58, 0x6a, 0x65, 0x11, 0x8c, 0x2d,
	0x4f, 0x36, 0x74, 0x62, 0x79, 0x45, 0x5a, 0xce, 0xc0, 0xa9, 0xe5, 0x0c, 0xaa, 0x6f, 0xc2, 0x1b,
	0xa7, 0x1a, 0x9b, 0x58, 0xaf, 0xff, 0x5e, 0x82, 0xcb, 0x0d, 0xee, 0x23, 0x02, 0x2f, 0x2f, 0x1c,
	0xc8, 0xda, 0x39, 0x07, 0x29, 0xb3, 0xf7, 0x6a, 0xfd, 0xe2, 0xdc, 0xc9, 0x5c, 0xd4, 0x82, 0x70,
	0xee, 0x8c, 0x54, 0xcf, 0xef, 0x30, 0x63, 0xaa, 0x77, 0x2e, 0xca, 0x9c, 0x4e, 0x3a, 0x02, 0x10,
	0x9d, 0xb2, 0xb3, 0xff, 0x68, 0xf4, 0x77, 0x85, 0xfa, 0xe0, 0x7f, 0x2b, 0x26, 0x12, 0xd4, 0x95,
	0xa3, 0xf8, 0xba, 0x59, 0x0f, 0x8f, 0x87, 0x1a, 0x38, 0x19, 0x6a, 0xe0, 0xd7, 0x50, 0x03, 0x1f,
	0x47, 0x5a, 0xee, 0x64, 0xa4, 0xe5, 0x7e, 0x8c, 0xb4, 0xdc, 0xcb, 0xe9, 0xb3, 0xb6, 0xb5, 0xf0,
	0x76, 0xa4, 0xd7, 0x4f, 0xf4, 0x43, 0xcc, 0xf7, 0x57, 0x93, 0xd7, 0xe3, 0xde, 0x9f, 0x00, 0x00,
	0x00, 0xff, 0xff, 0x5e, 0xcf, 0x6d, 0xbf, 0x03, 0x05, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MsgClient is the client API for Msg service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MsgClient interface {
	UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error)
	TransferTx(ctx context.Context, in *MsgTransferTx, opts ...grpc.CallOption) (*MsgTransferTxResponse, error)
	MintBurnTradingBtc(ctx context.Context, in *MsgMintBurnTradingBtc, opts ...grpc.CallOption) (*MsgMintBurnTradingBtcResponse, error)
}

type msgClient struct {
	cc grpc1.ClientConn
}

func NewMsgClient(cc grpc1.ClientConn) MsgClient {
	return &msgClient{cc}
}

func (c *msgClient) UpdateParams(ctx context.Context, in *MsgUpdateParams, opts ...grpc.CallOption) (*MsgUpdateParamsResponse, error) {
	out := new(MsgUpdateParamsResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.zkos.Msg/UpdateParams", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) TransferTx(ctx context.Context, in *MsgTransferTx, opts ...grpc.CallOption) (*MsgTransferTxResponse, error) {
	out := new(MsgTransferTxResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.zkos.Msg/TransferTx", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *msgClient) MintBurnTradingBtc(ctx context.Context, in *MsgMintBurnTradingBtc, opts ...grpc.CallOption) (*MsgMintBurnTradingBtcResponse, error) {
	out := new(MsgMintBurnTradingBtcResponse)
	err := c.cc.Invoke(ctx, "/twilightproject.nyks.zkos.Msg/MintBurnTradingBtc", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MsgServer is the server API for Msg service.
type MsgServer interface {
	UpdateParams(context.Context, *MsgUpdateParams) (*MsgUpdateParamsResponse, error)
	TransferTx(context.Context, *MsgTransferTx) (*MsgTransferTxResponse, error)
	MintBurnTradingBtc(context.Context, *MsgMintBurnTradingBtc) (*MsgMintBurnTradingBtcResponse, error)
}

// UnimplementedMsgServer can be embedded to have forward compatible implementations.
type UnimplementedMsgServer struct {
}

func (*UnimplementedMsgServer) UpdateParams(ctx context.Context, req *MsgUpdateParams) (*MsgUpdateParamsResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateParams not implemented")
}
func (*UnimplementedMsgServer) TransferTx(ctx context.Context, req *MsgTransferTx) (*MsgTransferTxResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TransferTx not implemented")
}
func (*UnimplementedMsgServer) MintBurnTradingBtc(ctx context.Context, req *MsgMintBurnTradingBtc) (*MsgMintBurnTradingBtcResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method MintBurnTradingBtc not implemented")
}

func RegisterMsgServer(s grpc1.Server, srv MsgServer) {
	s.RegisterService(&_Msg_serviceDesc, srv)
}

func _Msg_UpdateParams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgUpdateParams)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).UpdateParams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.zkos.Msg/UpdateParams",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).UpdateParams(ctx, req.(*MsgUpdateParams))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_TransferTx_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgTransferTx)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).TransferTx(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.zkos.Msg/TransferTx",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).TransferTx(ctx, req.(*MsgTransferTx))
	}
	return interceptor(ctx, in, info, handler)
}

func _Msg_MintBurnTradingBtc_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MsgMintBurnTradingBtc)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MsgServer).MintBurnTradingBtc(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/twilightproject.nyks.zkos.Msg/MintBurnTradingBtc",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MsgServer).MintBurnTradingBtc(ctx, req.(*MsgMintBurnTradingBtc))
	}
	return interceptor(ctx, in, info, handler)
}

var Msg_serviceDesc = _Msg_serviceDesc
var _Msg_serviceDesc = grpc.ServiceDesc{
	ServiceName: "twilightproject.nyks.zkos.Msg",
	HandlerType: (*MsgServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "UpdateParams",
			Handler:    _Msg_UpdateParams_Handler,
		},
		{
			MethodName: "TransferTx",
			Handler:    _Msg_TransferTx_Handler,
		},
		{
			MethodName: "MintBurnTradingBtc",
			Handler:    _Msg_MintBurnTradingBtc_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "twilightproject/nyks/zkos/tx.proto",
}

func (m *MsgUpdateParams) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParams) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParams) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	{
		size, err := m.Params.MarshalToSizedBuffer(dAtA[:i])
		if err != nil {
			return 0, err
		}
		i -= size
		i = encodeVarintTx(dAtA, i, uint64(size))
	}
	i--
	dAtA[i] = 0x12
	if len(m.Authority) > 0 {
		i -= len(m.Authority)
		copy(dAtA[i:], m.Authority)
		i = encodeVarintTx(dAtA, i, uint64(len(m.Authority)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgUpdateParamsResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgUpdateParamsResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgUpdateParamsResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgTransferTx) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferTx) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferTx) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.ZkOracleAddress) > 0 {
		i -= len(m.ZkOracleAddress)
		copy(dAtA[i:], m.ZkOracleAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.ZkOracleAddress)))
		i--
		dAtA[i] = 0x22
	}
	if m.TxFee != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.TxFee))
		i--
		dAtA[i] = 0x18
	}
	if len(m.TxByteCode) > 0 {
		i -= len(m.TxByteCode)
		copy(dAtA[i:], m.TxByteCode)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TxByteCode)))
		i--
		dAtA[i] = 0x12
	}
	if len(m.TxId) > 0 {
		i -= len(m.TxId)
		copy(dAtA[i:], m.TxId)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TxId)))
		i--
		dAtA[i] = 0xa
	}
	return len(dAtA) - i, nil
}

func (m *MsgTransferTxResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgTransferTxResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgTransferTxResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func (m *MsgMintBurnTradingBtc) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMintBurnTradingBtc) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMintBurnTradingBtc) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	if len(m.TwilightAddress) > 0 {
		i -= len(m.TwilightAddress)
		copy(dAtA[i:], m.TwilightAddress)
		i = encodeVarintTx(dAtA, i, uint64(len(m.TwilightAddress)))
		i--
		dAtA[i] = 0x2a
	}
	if len(m.EncryptScalar) > 0 {
		i -= len(m.EncryptScalar)
		copy(dAtA[i:], m.EncryptScalar)
		i = encodeVarintTx(dAtA, i, uint64(len(m.EncryptScalar)))
		i--
		dAtA[i] = 0x22
	}
	if len(m.QqAccount) > 0 {
		i -= len(m.QqAccount)
		copy(dAtA[i:], m.QqAccount)
		i = encodeVarintTx(dAtA, i, uint64(len(m.QqAccount)))
		i--
		dAtA[i] = 0x1a
	}
	if m.BtcValue != 0 {
		i = encodeVarintTx(dAtA, i, uint64(m.BtcValue))
		i--
		dAtA[i] = 0x10
	}
	if m.MintOrBurn {
		i--
		if m.MintOrBurn {
			dAtA[i] = 1
		} else {
			dAtA[i] = 0
		}
		i--
		dAtA[i] = 0x8
	}
	return len(dAtA) - i, nil
}

func (m *MsgMintBurnTradingBtcResponse) Marshal() (dAtA []byte, err error) {
	size := m.Size()
	dAtA = make([]byte, size)
	n, err := m.MarshalToSizedBuffer(dAtA[:size])
	if err != nil {
		return nil, err
	}
	return dAtA[:n], nil
}

func (m *MsgMintBurnTradingBtcResponse) MarshalTo(dAtA []byte) (int, error) {
	size := m.Size()
	return m.MarshalToSizedBuffer(dAtA[:size])
}

func (m *MsgMintBurnTradingBtcResponse) MarshalToSizedBuffer(dAtA []byte) (int, error) {
	i := len(dAtA)
	_ = i
	var l int
	_ = l
	return len(dAtA) - i, nil
}

func encodeVarintTx(dAtA []byte, offset int, v uint64) int {
	offset -= sovTx(v)
	base := offset
	for v >= 1<<7 {
		dAtA[offset] = uint8(v&0x7f | 0x80)
		v >>= 7
		offset++
	}
	dAtA[offset] = uint8(v)
	return base
}
func (m *MsgUpdateParams) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.Authority)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = m.Params.Size()
	n += 1 + l + sovTx(uint64(l))
	return n
}

func (m *MsgUpdateParamsResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgTransferTx) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	l = len(m.TxId)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TxByteCode)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	if m.TxFee != 0 {
		n += 1 + sovTx(uint64(m.TxFee))
	}
	l = len(m.ZkOracleAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgTransferTxResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func (m *MsgMintBurnTradingBtc) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	if m.MintOrBurn {
		n += 2
	}
	if m.BtcValue != 0 {
		n += 1 + sovTx(uint64(m.BtcValue))
	}
	l = len(m.QqAccount)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.EncryptScalar)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	l = len(m.TwilightAddress)
	if l > 0 {
		n += 1 + l + sovTx(uint64(l))
	}
	return n
}

func (m *MsgMintBurnTradingBtcResponse) Size() (n int) {
	if m == nil {
		return 0
	}
	var l int
	_ = l
	return n
}

func sovTx(x uint64) (n int) {
	return (math_bits.Len64(x|1) + 6) / 7
}
func sozTx(x uint64) (n int) {
	return sovTx(uint64((x << 1) ^ uint64((int64(x) >> 63))))
}
func (m *MsgUpdateParams) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParams: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParams: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Authority", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.Authority = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field Params", wireType)
			}
			var msglen int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				msglen |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if msglen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + msglen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			if err := m.Params.Unmarshal(dAtA[iNdEx:postIndex]); err != nil {
				return err
			}
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgUpdateParamsResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgUpdateParamsResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferTx) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferTx: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferTx: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxId", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxId = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 2:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxByteCode", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TxByteCode = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 3:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field TxFee", wireType)
			}
			m.TxFee = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.TxFee |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field ZkOracleAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.ZkOracleAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgTransferTxResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgTransferTxResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgTransferTxResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMintBurnTradingBtc) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMintBurnTradingBtc: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMintBurnTradingBtc: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		case 1:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field MintOrBurn", wireType)
			}
			var v int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				v |= int(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			m.MintOrBurn = bool(v != 0)
		case 2:
			if wireType != 0 {
				return fmt.Errorf("proto: wrong wireType = %d for field BtcValue", wireType)
			}
			m.BtcValue = 0
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				m.BtcValue |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
		case 3:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field QqAccount", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.QqAccount = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 4:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field EncryptScalar", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.EncryptScalar = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		case 5:
			if wireType != 2 {
				return fmt.Errorf("proto: wrong wireType = %d for field TwilightAddress", wireType)
			}
			var stringLen uint64
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return ErrIntOverflowTx
				}
				if iNdEx >= l {
					return io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				stringLen |= uint64(b&0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			intStringLen := int(stringLen)
			if intStringLen < 0 {
				return ErrInvalidLengthTx
			}
			postIndex := iNdEx + intStringLen
			if postIndex < 0 {
				return ErrInvalidLengthTx
			}
			if postIndex > l {
				return io.ErrUnexpectedEOF
			}
			m.TwilightAddress = string(dAtA[iNdEx:postIndex])
			iNdEx = postIndex
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func (m *MsgMintBurnTradingBtcResponse) Unmarshal(dAtA []byte) error {
	l := len(dAtA)
	iNdEx := 0
	for iNdEx < l {
		preIndex := iNdEx
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return ErrIntOverflowTx
			}
			if iNdEx >= l {
				return io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= uint64(b&0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		fieldNum := int32(wire >> 3)
		wireType := int(wire & 0x7)
		if wireType == 4 {
			return fmt.Errorf("proto: MsgMintBurnTradingBtcResponse: wiretype end group for non-group")
		}
		if fieldNum <= 0 {
			return fmt.Errorf("proto: MsgMintBurnTradingBtcResponse: illegal tag %d (wire type %d)", fieldNum, wire)
		}
		switch fieldNum {
		default:
			iNdEx = preIndex
			skippy, err := skipTx(dAtA[iNdEx:])
			if err != nil {
				return err
			}
			if (skippy < 0) || (iNdEx+skippy) < 0 {
				return ErrInvalidLengthTx
			}
			if (iNdEx + skippy) > l {
				return io.ErrUnexpectedEOF
			}
			iNdEx += skippy
		}
	}

	if iNdEx > l {
		return io.ErrUnexpectedEOF
	}
	return nil
}
func skipTx(dAtA []byte) (n int, err error) {
	l := len(dAtA)
	iNdEx := 0
	depth := 0
	for iNdEx < l {
		var wire uint64
		for shift := uint(0); ; shift += 7 {
			if shift >= 64 {
				return 0, ErrIntOverflowTx
			}
			if iNdEx >= l {
				return 0, io.ErrUnexpectedEOF
			}
			b := dAtA[iNdEx]
			iNdEx++
			wire |= (uint64(b) & 0x7F) << shift
			if b < 0x80 {
				break
			}
		}
		wireType := int(wire & 0x7)
		switch wireType {
		case 0:
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				iNdEx++
				if dAtA[iNdEx-1] < 0x80 {
					break
				}
			}
		case 1:
			iNdEx += 8
		case 2:
			var length int
			for shift := uint(0); ; shift += 7 {
				if shift >= 64 {
					return 0, ErrIntOverflowTx
				}
				if iNdEx >= l {
					return 0, io.ErrUnexpectedEOF
				}
				b := dAtA[iNdEx]
				iNdEx++
				length |= (int(b) & 0x7F) << shift
				if b < 0x80 {
					break
				}
			}
			if length < 0 {
				return 0, ErrInvalidLengthTx
			}
			iNdEx += length
		case 3:
			depth++
		case 4:
			if depth == 0 {
				return 0, ErrUnexpectedEndOfGroupTx
			}
			depth--
		case 5:
			iNdEx += 4
		default:
			return 0, fmt.Errorf("proto: illegal wireType %d", wireType)
		}
		if iNdEx < 0 {
			return 0, ErrInvalidLengthTx
		}
		if depth == 0 {
			return iNdEx, nil
		}
	}
	return 0, io.ErrUnexpectedEOF
}

var (
	ErrInvalidLengthTx        = fmt.Errorf("proto: negative length found during unmarshaling")
	ErrIntOverflowTx          = fmt.Errorf("proto: integer overflow")
	ErrUnexpectedEndOfGroupTx = fmt.Errorf("proto: unexpected end of group")
)
